### ISSUE TITLE
Running MARSSIM

### ISSUE THREAD

**Issue by mdpiper** [csdms/help-desk#1]
@alimaye writes:

> Hi Mark,
I'm writing with a question about running a model through CSDMS. I came across some of the helpful tutorials you authored on the website. I'd like to run the model MARSSIM, along the lines described in this tutorial:
https://csdms.colorado.edu/wiki/CMT_Tutorial_Marssim
In the last few weeks Lynn McCready and colleagues have set me up with CU login credentials and HPC account on blanca. I'm writing to check which interface I should use to run MARSSIM (i.e., CMT vs. WMT). I successfully logged into WMT but did not see a way to select the MARSSIM model. With CMT, the updated version of the GUI showed beach as the only login option, and the login failed (despite a VPN connection to colorado.edu).
Thanks for your help. I'm excited to get started with these great modeling tools!
Ajay

**Comment by mdpiper** [comment]
I spoke with @alimaye on the phone & explained that CMT no longer exists, and that there is no MARSSIM component in WMT. I'll try to build MARSSIM on Blanca, which should meet his needs.

**Comment by mdpiper** [comment]
We also need to remove obsolete pages like https://csdms.colorado.edu/wiki/CMT_Tutorial_Marssim from the CSDMS wiki. This is #2.

**Comment by mdpiper** [comment]
@alimaye I installed MARSSIM on blanca in `/pl/active/csdms` (the CSDMS Petalibrary). You'll need to add this path to your PATH variable to run it:

    PATH=/pl/active/csdms/local/bin:$PATH

To check that MARSSIM works, I downloaded the Callisto example from the [MARSSIM model page](https://csdms.colorado.edu/wiki/Model:MARSSIM) to `/pl/active/csdms/scratch/Callisto`. I found that had to change two files from the example (just uppercasing the names) to get the model to run:

    cp marssim.prm MARSSIM.PRM
    cp inelev.dat INELEV.DAT

From a blanca compute node, in the `Callisto` directory, I ran MARSSIM with

    run_marssim >& log &

All you really need is `run_marssim`, but it prints to the console on each update, so I redirected that info to `log`.

Good luck! Let me know how it goes.

**Comment by alimaye** [comment]
@mdpiper I got to the point of running the simulation with `run_marssim`, however the command was not found. Perhaps I do not have the proper permissions? I added the path per the instructions, but cannot see `run_marssim`

**Comment by mdpiper** [comment]
@alimaye Could you please copy/paste the command and error message?

**Comment by alimaye** [comment]
`[ajli7272@bnode0316 inputFiles]$ echo $PATH
/pl/active/csdms/local/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/dell/srvadmin/bin
[ajli7272@bnode0316 inputFiles]$ run_marssim
bash: run_marssim: command not found`

**Comment by mdpiper** [comment]
@alimaye I see that the permissions on `/pl/active/csdms` are restricted:

```
[mapi8461@bnode0316 csdms]$ ls -ld /pl/active/csdms/
drwxrws--- 10 huttone huttonegrp 9 Mar 27 12:19 /pl/active/csdms/
```

I think this may be the problem. Can you `cd` to this directory? (My hunch is no.)

@mcflugen Could you please `chmod +rx` this directory? I don't have permissions to do so.

**Comment by alimaye** [comment]
Correct, I cannot `cd` to `/pl/active/csdms/`

**Comment by mcflugen** [comment]
@mdpiper I've changed the permissions on `/pl/active/csdms`.
```bash
$ ls -ld /pl/active/csdms/
drwxrws--x. 10 huttone huttonegrp 9 Mar 27 12:19 /pl/active/csdms/
```
Does that do the trick?

**Comment by alimaye** [comment]
Thanks @mcflugen 
@mdpiper now looking for the fortran library:

`$ /pl/active/csdms/local/bin/run_marssim
/pl/active/csdms/local/bin/run_marssim: error while loading shared libraries: libgfortran.so.3: cannot open shared object file: No such file or directory`

```

**Comment by mdpiper** [comment]
@alimaye You'll have to load a compiler module that supplies the Fortran library. I built MARSSIM with gcc, but I think intel would also work.
```
$ module load gcc
```
I'll update the instructions upthread for posterity, as well.

**Comment by alimaye** [comment]
Got it - up and running!
