### ISSUE TITLE
Issues for testing Pymt demo Jupyter Notebooks

### ISSUE THREAD

**Issue by gantian127** [csdms/help-desk#10]
I tried to test all the Pymt example Jupyter Notebooks (https://github.com/csdms/pymt/tree/master/docs/demos) on HydroShare Jupyterhub and had the following issues. Thanks!

- [x] **subside**: 
issue 1: import "plugin" error
![image](https://user-images.githubusercontent.com/5016511/65550075-0afc7780-dedc-11e9-9fc3-b5acc4ae707c.png)

- [x] **Sedflux3D**: 
issue 1: import "plugin" error
issue 2: no "get_current_time", "get_time_step" attribute (But most of the other cells seem to work well)
![image](https://user-images.githubusercontent.com/5016511/65550188-49923200-dedc-11e9-9999-e22f092f0229.png)

- [x] **child**:
issue 1: import "plugin" error
issue 2: no "child" model 
![image](https://user-images.githubusercontent.com/5016511/65550429-c7563d80-dedc-11e9-86aa-36dc75af1899.png)

- [x] **Sedflux3D_and_child**:
issue 1: import "plugin" error
issue 2: no "child" model

- [ ] **Example_01_Basic_User_GIPL/ Example_02_GIPL_ECSimpleSnow: (may not be an issue)**
A user needs to run the following command in the HydroShare Jupyterhub terminal before running the code:
 conda install pymt_gipl pymt_ecsimplesnow seaborn -c conda-forge

**Comment by mdpiper** [comment]
Closed with https://github.com/csdms/pymt/pull/94. Thanks, @gantian127!
