### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by Cracert** [csdms/help-desk#100]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:*
Robertsz

*First four characters of username:*
Robe

*Describe why you're signing up for an account:*
I plan to explore already published Labs and prepare some for my students. 

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
@Cracert You're all set. Please let me know if I can help with setting up logins for your students.

**Comment by Cracert** [comment]
Thank you @mdpiper. It was rally fast.
