### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by PINYI1** [csdms/help-desk#101]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:*
pin.a.yi

*First four characters of username:*
pin.

*Describe why you're signing up for an account:*
Student out of personal interest

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
@PINYI1 You're all set! Please let me know if you have any questions.
