### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by fmatthews666** [csdms/help-desk#102]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:* francism

*First four characters of username:* fran

*Describe why you're signing up for an account:* research purposes (PhD researcher)

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
@fmatthews666 You're all set! Let us know if you have any questions.
