### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by nicgaspar** [csdms/help-desk#103]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:*
nicgaspar

*First four characters of username:*
ngas

*Describe why you're signing up for an account:*
use for class assignments

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
You're all set, Nicole. Let me know if this works.

**Comment by nicgaspar** [comment]
Thank you Mark! I was able to log in. But I can no longer see the repo from my class. Do I need to do something to link to that?

**Comment by mdpiper** [comment]
Just click the nbgitpuller link from your repository. It'll populate the new login.
