### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by mdbehn** [csdms/help-desk#108]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:*
mdbehn

*First four characters of username:*

mdbe
*Describe why you're signing up for an account:*
CSDMS Annual Meeting Clinic

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
Hi Mark! You're all set.

**Comment by mdbehn** [comment]
Awesome — Thanks Mark!


Mark D. Behn
Boston College
Department of Earth and Environmental Sciences   
***@***.***
phone: (617) 552-2180

On May 13, 2021 at 2:01:45 PM, Mark Piper ***@***.***) wrote:

Hi Mark! You're all set.
