### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by Joseph-A-Mason** [csdms/help-desk#109]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:*
Jamason

*First four characters of username:*
maso

*Describe why you're signing up for an account:*
for clinic in CSDMS 2021 Annual Meeting

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
Hi @Joseph-A-Mason -- you're all set!
