### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by rdmadoff** [csdms/help-desk#110]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:*
rdmadoff

*First four characters of username:*
rdma

*Describe why you're signing up for an account:*
2021 Clinic

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
Hi @rdmadoff -- you're all set to login!
