### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by Lvulis** [csdms/help-desk#111]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:*
lvulis

*First four characters of username:*
lvul

*Describe why you're signing up for an account:*
I'm a registered participant in the JupyterHub workshop at CSDMS 2021. In general I'm interested in learning more about land surface modelling capabilities available thru JupyterHub.

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
Hi @Lvulis -- you're all set to login!

**Comment by Lvulis** [comment]
Hi @mdpiper, I messed up and can't remember my password. It is possible to reset this? Sorry to interrupt during the clinic.

**Comment by mdpiper** [comment]
Hi Lawrence -- it looks like you haven't logged in before & the JupyterHub software doesn't let me change a password for a user that hasn't logged in. You can make a new username at https://csdms.rc.colorado.edu/hub/signup. Let me know when you do, and I'll immediately approve it, then you can login.

**Comment by Lvulis** [comment]
Hi Mark, thanks for responding very fast! That's fair, should've tried my login before the clinic. I just generated a new account:

_CSDMS username:_
lvulis

_First four characters of username:_
lvul

**Comment by mdpiper** [comment]
Got it -- you should be set to login, Lawrence!

**Comment by Lvulis** [comment]
Thank you!
