### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by loroberge** [csdms/help-desk#113]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:*
lroberge

*First four characters of username:*
lrob

*Describe why you're signing up for an account:*
Signing up for CSDMS clinic "Under the Hood: Landscape Evolution Modeling with TerrainBento and Landlab” 

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
Hi @loroberge -- I don't see a login for you on the JupyterHub. You have to make a login name and password at https://csdms.rc.colorado.edu/hub/signup. This is separate from your CSDMS username. Let me know what login name you pick so I can find it in the list and approve it. After this, you'll be able to login at https://csdms.rc.colorado.edu/hub/login.

**Comment by mdpiper** [comment]
@loroberge You're all set!
