### ISSUE TITLE
Adding to EKT labs on CSDMS website

### ISSUE THREAD

**Issue by bhunter2** [csdms/help-desk#114]
Hi there,

A group of us from the ESPIn summer course 2020 are hoping to get the lab we created on the CSMDS EKT website. I am not sure if I did everything/linked to things properly, so please let me know what else you need from me or if you find errors!
Best,
Brooke Hunter (University of Oregon - bhunter2@uoregon.edu).

URL of your EKT Lab wiki -https://csdms.colorado.edu/wiki/Lab-0023

URL to download Jupyter Notebooks - https://github.com/espin-2020/precipitation_lanscape_evolution/tree/master/Final%20Version

Python packages used for Jupyter Notebooks - landlab, numpy, random, matplotlib, and pandas
URL to download input datasets (optional) -  https://github.com/espin-2020/precipitation_lanscape_evolution/tree/master/Final%20Version

**Comment by mdpiper** [comment]
Hi Brooke--this looks great! I'll get it set up on the CSDMS JupyterHub (although maybe not this week). Thank you to all of you for your work!

**Comment by mdpiper** [comment]
I added an _nbgitpuller_ link to the lab page so it can be run on the CSDMS JupyterHub. It runs perfectly. The lab is live!

**Comment by bhunter2** [comment]
Hi Mark! I realized that the drawings/images are not showing up when I run the notebook. I think maybe this is an issue with how I reference them in the code.  I am not quite sure how to fix this though. Do you have any suggestions?


![Hunter_DrawingJPGerror](https://user-images.githubusercontent.com/41830925/122263163-f8ce2400-ce8a-11eb-8de6-afab9d2848c9.PNG)

`## Conceptual Model

**Comment by mdpiper** [comment]
Hey Brooke--I'll figure this out & make a PR into your repository. I think I had to do similar modifications in other notebooks.

**Comment by mdpiper** [comment]
Hi Brooke--I think I fixed the problem. I sent a PR to your group; it's https://github.com/espin-2020/precipitation_lanscape_evolution/pull/4.

**Comment by mdpiper** [comment]
Closing with above fix.
