### ISSUE TITLE
JupyterHub login doesn't work

### ISSUE THREAD

**Issue by Joseph-A-Mason** [csdms/help-desk#122]
Sorry, I set up a login last week for the clinic run by Benjamin Campforts tomorrow, but the password doesn't seem to work today. Can I reset it? CSDMS username Jamason, first four characters of JupyterHub username: maso

**Comment by mdpiper** [comment]
Hi @Joseph-A-Mason -- I think I can fix this. Would you please go to https://csdms.rc.colorado.edu/hub/signup and enter the same username (starting with "maso") and a new password? Let me know when you've done this (you can just respond here), and I'll approve it, then you can login.

If this doesn't work, I have a backup plan.

**Comment by Joseph-A-Mason** [comment]
Thanks, just tried that and got an error message

Joe


-------- Original message --------
From: Mark Piper ***@***.***>
Date: 5/19/21 3:44 PM (GMT-06:00)
To: csdms/help-desk ***@***.***>
Cc: Joseph Mason ***@***.***>, Mention ***@***.***>
Subject: Re: [csdms/help-desk] JupyterHub login doesn't work (#122)


Hi @Joseph-A-Mason<https://github.com/Joseph-A-Mason> -- I think I can fix this. Would you please go to https://csdms.rc.colorado.edu/hub/signup and enter the same username (starting with "maso") and a new password? Let me know when you've done this (you can just respond here), and I'll approve it, then you can login.

If this doesn't work, I have a backup plan.

**Comment by mdpiper** [comment]
OK, the backup plan is to create a new login. Let me know when you've done so & I'll approve it. You'll then be able to login.

**Comment by Joseph-A-Mason** [comment]
Okay, set up new login. First 4 characters of username: ja-m

Thanks


-------- Original message --------
From: Mark Piper ***@***.***>
Date: 5/19/21 4:12 PM (GMT-06:00)
To: csdms/help-desk ***@***.***>
Cc: Joseph Mason ***@***.***>, Mention ***@***.***>
Subject: Re: [csdms/help-desk] JupyterHub login doesn't work (#122)


OK, the backup plan is to create a new login. Let me know when you've done so & I'll approve it. You'll then be able to login.

**Comment by mdpiper** [comment]
OK, you're now all set to login.
