### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by eb-mars** [csdms/help-desk#123]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:* EmilyBamber

*First four characters of username:* Emil

*Describe why you're signing up for an account:* CSDMS clinic "Under the Hood: Landscape Evolution Modeling with TerrainBento and Landlab” 

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
Hi @eb-mars -- you're all set to login!
