### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by melguirro** [csdms/help-desk#129]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:*
Melguirro

*First four characters of username:*
melg

*Describe why you're signing up for an account:*
I have an interest in using Landlab for my PhD research project and I'll attend the ESPIn 2021.

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
Hi @melguirro -- you're all set!
