### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by GrasshopperAM** [csdms/help-desk#133]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:*
Grasshopper

*First four characters of username:*
Gras

*Describe why you're signing up for an account:*
Needed for participation in ESPIn 2021 course

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
Hi @GrasshopperAM -- you're all set!
