### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by josh-wolpert** [csdms/help-desk#136]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:*
jowolpert1

*First four characters of username:*
josh

*Describe why you're signing up for an account:*
I'm participating in the ESPIm 2021 summer school.

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
Hi @josh-wolpert -- you're all set!
