### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by angelmonsalve** [csdms/help-desk#138]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:*
Angelmonsalve

*First four characters of username:*
ange

*Describe why you're signing up for an account:*
I will be participating in the ESPIn 2021. Having access to this account it is required.

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
Hi @angelmonsalve -- you're all set!
