### ISSUE TITLE
installed pymt but hydrotrend is missing?

### ISSUE THREAD

**Issue by sakilcse** [csdms/help-desk#14]
hi, I installed pymt on a windows machine today and hydrotrend is missing. We are running this at IWM in collaboration with Dr. Overeem.
Upon installation we receive the following error:
![image](https://user-images.githubusercontent.com/13697834/69527256-221c1c00-0f96-11ea-9e10-a4ec722105d7.png)

What would we need to do to fix this issue? thank you

**Comment by mdpiper** [comment]
@sakilcse Hydrotrend isn't built on Windows for pymt.

That said, I was able to build hydrotrend and pymt_hydrotrend locally on a Windows machine and upload binaries. Here's how you can install them.

1. Open an Anaconda Prompt and create a new conda environment. Let's call it "hydro".

        conda create -n hydro python=3

1. Once it's created, activate it.

        conda activate hydro

1. Install hydrotrend, pymt, and pymt_hydrotrend. Note the use of the "mdpiper" and "conda-forge" channels, in that order. This step may take some time to complete.

        conda install pymt pymt_hydrotrend -c mdpiper -c conda-forge

When this install completes, you should be able to use hydrotrend in pymt. However, I make no guarantees -- while this works on my local machine, it didn't go through the conda-forge build process, so it may not work on yours.

**Comment by sakilcse** [comment]
@mdpiper Glad to see this solution. It is now working on my Windows Machine and Thanks to  Dr. Overeem for showing the right track.
