### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by npmoragoda** [csdms/help-desk#142]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:*
Nishanimoragoda

*First four characters of username:*
npmo

*Describe why you're signing up for an account:*
ESPIn Summer Program

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
Hi @npmoragoda -- you're all set!
