### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by mlh300** [csdms/help-desk#143]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:*Mlh

*First four characters of username:*mlh3

*Describe why you're signing up for an account:* I was asked to do it for preparation of ESPIn.

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
Hi @mlh300 -- you're all set!
