### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by taranguiz** [csdms/help-desk#148]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:*
Taranguiz

*First four characters of username:*
tara

*Describe why you're signing up for an account:*
I need it to participate in the ESPIn 2021 workshop

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
Hi @taranguiz -- you're all set!

**Comment by taranguiz** [comment]
thank you!

**Comment by mdpiper** [comment]
You're welcome!
