### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by zddubo22** [csdms/help-desk#149]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:* 
Zddubo22

*First four characters of username:* 
Zddu

*Describe why you're signing up for an account:*
I would like to use CSDMS JupyterHub for a school project I am working on, so that I do not have to host the server myself.

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
Hi @zddubo22 -- you're all set!

**Comment by zddubo22** [comment]
Hi @mdpiper , I think I may have made a typo in my password. Is there any way I can reset it?

**Comment by mdpiper** [comment]
Interestingly, if you've logged in once, I can recover a password, but if you haven't logged in, I can't. It's OK to make a new login & password at the signup page.

**Comment by zddubo22** [comment]
Ok, thank you. I'll be more careful.
