### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by zddubo22** [csdms/help-desk#150]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:* 
zdubosky

*First four characters of username:*
zdub

*Describe why you're signing up for an account:*
I would like to use CSDMS JupyterHub for a school project.

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by zddubo22** [comment]
It worked! Thank you.

**Comment by mdpiper** [comment]
👋 @zddubo22  -- The JupyterHub that's at [lab.openearthscape.org](https://lab.openearthscape.org/) (and used to be at [csdms.rc.colorado.edu](https://csdms.rc.colorado.edu/)) is getting retired. You can still access this Hub at [lab-old.openearthscape.org](https://lab-old.openearthscape.org/), but if there's anything you'd like to save from it, please do so by the end of August. Let me know if you'd like any help with this.

Would you like me to set up a login for you on our research Hub [jupyter.openearthscape.org](https://jupyter.openearthscape.org/)? (It's really the same thing, but its purpose is for research, while the "lab" Hub is for teaching.)

**Comment by zddubo22** [comment]
Hi Mark,

That would be really helpful, thank you.

Best,
Zack Dubosky

**Comment by mdpiper** [comment]
Done! Please follow [these instructions](https://csdms.colorado.edu/wiki/JupyterHubGitHubSignUp#The_first-time_login_process) for your first login, and let me know if you run into any problems, Zack.
