### ISSUE TITLE
Add "Cratered Landscapes" (ESPIn 2021) EKT Lab to Jupyter Hub

### ISSUE THREAD

**Issue by eb-mars** [csdms/help-desk#152]
Hi! Our "planetary" group from ESPIn 2021 would like to upload our cratering lab to the CSDMS Jupyter Hub. Below is the required information:

URL of EKT Lab wiki: https://csdms.colorado.edu/wiki/Lab-0025

URL of Jupyter Notebooks https://utexas.box.com/s/7uiy7vhe030o4rac1bc7gvb7z46m58im

Python packages used in notebook: numpy, landlab, random, matplotlib

**Comment by mdpiper** [comment]
@eb-mars Awesome! Thank you for doing this. I can help, but it'll be a little bit because I'm currently writing a proposal as if my job depended on it (which it does). I'll touch base with you soon.

**Comment by eb-mars** [comment]
> @eb-mars Awesome! Thank you for doing this. I can help, but it'll be a little bit because I'm currently writing a proposal as if my job depended on it (which it does). I'll touch base with you soon.

No worries! No rush on this :) Good luck with the proposal.

**Comment by mdpiper** [comment]
@eb-mars Your notebook is all set to run on the CSDMS JupyterHub. I checked & it runs flawlessly out of the box. Thank you for putting together such an excellent lab. May I tweet an announcement that this new lab is ready to run?

**Comment by eb-mars** [comment]
Thanks @mdpiper !! It wouldn't have been possible without you and the ESPIn team! Please do tweet the announcement :D

**Comment by mdpiper** [comment]
@eb-mars Will do! Thanks again!
