### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by monsieurbungle** [csdms/help-desk#153]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:*
Mrbungle

*First four characters of username:*
Mons

*Describe why you're signing up for an account:*
I want to learn how to build Earth Surface Models

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
Hi @monsieurbungle (that's an entertaining username) -- you're all set! And just to be careful, your login is `Mr_Bungle` on the JHub.
