### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by BenjaminLehmann** [csdms/help-desk#155]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:*
BenjaminLehmann

*First four characters of username:*
Benj

*Describe why you're signing up for an account:*
I want to learn to use the different landscape evolution model that CSDMS proposed and learn to code in Python in the same time.

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
Hi @BenjaminLehmann -- you're all set!
