### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by smguit24** [csdms/help-desk#157]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:*smguit24

*First four characters of username:*smgu

*Describe why you're signing up for an account:*class assignment 

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by smguit24** [comment]
hi I am trying to sign up for an account for a class assignment

**Comment by mdpiper** [comment]
Hi @smguit24 --you're all set!
