### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by iamsaswata** [csdms/help-desk#158]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:*Snandi

*First four characters of username:*snan

*Describe why you're signing up for an account:*Statistical analysis in Python related to hydrology and climate change

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
Hi @iamsaswata — you’re all set!
