### ISSUE TITLE
CSDMS Jupyter Hub lost password...

### ISSUE THREAD

**Issue by bhunter2** [csdms/help-desk#160]
Hi,
Unfortunately I am unable to log into my CSDMS JupyterHub account... I seemed to have misplaced my password. I cannot find a "lost password" option. Is there a way to get back into my account/reset the password?
Best,
Brooke

**Comment by mdpiper** [comment]
Got it--I found "bhunter2". Would you please go to the [signup page](https://csdms.rc.colorado.edu/hub/signup) again, use "bhunter2" as your username, and choose a password? When you've done this, let me know & I'll approve the login.

**Comment by bhunter2** [comment]
Done!

**Comment by mdpiper** [comment]
OK! Go to the [login page](https://csdms.rc.colorado.edu/hub/login) and you should be able to login with your username and new password. And all of your files should still be there.
