### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by cele5425** [csdms/help-desk#161]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*sicel11*

*sice*

*I would like to learn Hydrological modelling as well model calibration *

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
Hi @cele5425 -- you can now login!
