### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by KeweiZhao** [csdms/help-desk#164]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:* Kewei

*First four characters of username:* kewe

*Describe why you're signing up for an account:* I would like to model biogeochemical cycles.

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
Hi, @KeweiZhao -- you're all set! Let us know if you run into any problems on the CSDMS JupyterHub!
