### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by degabbersaurus** [csdms/help-desk#165]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:*
Jvanruitenbeek

*First four characters of username:*
Jvan

*Describe why you're signing up for an account:*
I am a Hydrology student from Amsterdam doing a Master Thesis on Permafrost, and I want to see if I can use and contribute to some of the models!

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
Hi @degabbersaurus -- you're all set to login. Happy coding!

**Comment by mdpiper** [comment]
Hi again @degabbersaurus! I just saw that I may have forgotten to press the "Authorize" button yesterday. If you've tried to login but it didn't work, please try again. I'm sorry about that.

**Comment by degabbersaurus** [comment]
no problem! I got it running and can take the Jupyter Lab courses on CSDMS. Its all working now ;)
