### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by moupyali** [csdms/help-desk#166]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:*
Moupyali

*First four characters of username:*
Moup

*Describe why you're signing up for an account:*
For educational purpose 
Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
Hi @moupyali -- we noticed that you're not a CSDMS member yet, which is a condition for using our JupyterHub. Would you please sign up at this link https://csdms.colorado.edu/wiki/Join_CSDMS and let me know when you've done so?
