### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by cfassett** [csdms/help-desk#169]
Thank you for signing up to use the CSDMS JupyterHub. Please provide your CSDMS username and a brief description of why you're signing up (a sentence is fine).

*CSDMS username:*
Cfassett

*Describe why you're signing up for an account:*
Want to try out some of the tutorial notebooks.  Maybe get smarter.  :)

Once you've completed this step, you'll typically get approval within one business day.

**Comment by mdpiper** [comment]
👋 @cfassett -- you're all set! Check out the info at https://csdms.colorado.edu/wiki/JupyterHub and let us know if you have any questions.

Also, if you find a way to become smarter, please let me know; I could use some help.
