### ISSUE TITLE
Local installation of Frost Number Model notebook? 

### ISSUE THREAD

**Issue by iovereem** [csdms/help-desk#17]
hi there, 

I opened the Frost Number model example from the pymt read the docs website, and launched it in Binder. 
https://hub.gke.mybinder.org/user/csdms-pymtbd2npumi/notebooks/notebooks/frost_number.ipynb

However, I want a local installation of this notebook instead, so i follow the instructions in the first section of the notebook. The download of the notebook is stated to be here: 
curl -O https://raw.githubusercontent.com/csdms/pymt/master/docs/demos/frost_number.ipynb

If I use that command in my terminal window, it returns the following error message. 
[W 09:57:47.814 NotebookApp] 400 GET /api/contents/NOTEBOOKS/PERMAFROST/frost_number.ipynb?type=notebook&_=1578589067677 (::1): Unreadable Notebook: /Users/overeem/NOTEBOOKS/PERMAFROST/frost_number.ipynb NotJSONError("Notebook does not appear to be JSON: '404: Not Found\\n'...")

Still a file image appears in my local directory, but it does not open as a jupyter notebook. 

Is it better to tell users to do the conda install and export the binder notebook?

**Comment by mdpiper** [comment]
@gantian127 If you have a moment, would you please fix this and send a PR back to the pymt repository? The notebooks have been moved to a top-level directory in the repository & the links need updating. Thank you!

**Comment by gantian127** [comment]
@mdpiper I will work on it. Thanks!

**Comment by mdpiper** [comment]
Fixed with https://github.com/csdms/pymt/pull/105.
