### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by aeckland2696** [csdms/help-desk#171]
Thank you for signing up to use the CSDMS JupyterHub. Please provide your CSDMS username and a brief description of why you're signing up (a sentence is fine).

*CSDMS username: Aeckland*

*Describe why you're signing up for an account: to use the jupyter hub*

Once you've completed this step, you'll typically get approval within one business day.

**Comment by mdpiper** [comment]
👋 @aeckland2696 -- you're all set. Please follow [these instructions](https://csdms.colorado.edu/wiki/JupyterHubGitHubSignUp) for your first login (and let me know if I can improve the instructions, too).
