### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by KevRozmiarek** [csdms/help-desk#172]
Thank you for signing up to use the CSDMS JupyterHub. Please provide your CSDMS username and a brief description of why you're signing up (a sentence is fine).

*CSDMS username:*
KevinRozmiarek
*Describe why you're signing up for an account:*
I have an account with lab.openearthscape and I am looking to transition to the new jupyter.openearthscape

:muscle: 

Once you've completed this step, you'll typically get approval within one business day.

**Comment by mdpiper** [comment]
👋 @KevRozmiarek  -- you're all set. Please follow [these instructions](https://csdms.colorado.edu/wiki/JupyterHubGitHubSignUp) for your first login (and let me know if I can improve the instructions, too).

🚀 🚀 🚀
