### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by josiearcuri** [csdms/help-desk#173]
Thank you for signing up to use the CSDMS JupyterHub. Please provide your CSDMS username and a brief description of why you're signing up (a sentence is fine).

*CSDMS username:* 
JArcuri

*Describe why you're signing up for an account:*
for collaborating in geomorph seminar, spring 2022

Once you've completed this step, you'll typically get approval within one business day.

**Comment by mdpiper** [comment]
👋 @josiearcuri  -- you're all set. Please follow [these instructions](https://csdms.colorado.edu/wiki/JupyterHubGitHubSignUp) for your first login (and let me know if I can improve the instructions, too).
