### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by kalcan83** [csdms/help-desk#174]
Thank you for signing up to use the CSDMS JupyterHub. Please provide your CSDMS username and a brief description of why you're signing up (a sentence is fine).

*CSDMS username:* kalcan

*Describe why you're signing up for an account:* I thought I already had access after the 2021 CSDMS conference. I wanted to review what I learned last year and see if I could get a model working.

Thanks,

Kelly

Once you've completed this step, you'll typically get approval within one business day.

**Comment by mdpiper** [comment]
👋 @kalcan83 -- you're all set. Please follow [these instructions](https://csdms.colorado.edu/wiki/JupyterHubGitHubSignUp) for your first login (and let me know if I can improve the instructions, too).

I see that you have a login on [lab.openearthscape.org](https://lab.openearthscape.org). (This is the JupyterHub that was used in the 2021 CSDMS meeting, but we changed the URL.) Would you like help regaining access to this Hub?
