### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by iovereem** [csdms/help-desk#175]
Thank you for signing up to use the CSDMS JupyterHub. Please provide your CSDMS username and a brief description of why you're signing up (a sentence is fine).

*CSDMS username:*
overeem

*Describe why you're signing up for an account:*
switch to the new hub for research and teaching

Once you've completed this step, you'll typically get approval within one business day.

**Comment by mdpiper** [comment]
👋 @iovereem  -- you're all set. I'm sorry I didn't think of this earlier. Please follow [these instructions](https://csdms.colorado.edu/wiki/JupyterHubGitHubSignUp) for your first login (and let me know if I can improve the instructions, too).

@kettner, @gantian127 -- I've also added you to the allow list, so like @iovereem, you can use the instructions above if you'd like to login to the *jupyter* Hub.
