### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by philippesteer** [csdms/help-desk#176]
Thank you for signing up to use the CSDMS JupyterHub. Please provide your CSDMS username and a brief description of why you're signing up (a sentence is fine).

*CSDMS username:* philippe.steer

*Describe why you're signing up for an account:* I am signing up to get access to both some elements of Landlab for some research activities and some teaching materials that I would like to use for some classrooms. Thanks!

Once you've completed this step, you'll typically get approval within one business day.

**Comment by mdpiper** [comment]
👋 @philippesteer -- you're all set! Please follow [these instructions](https://csdms.colorado.edu/wiki/JupyterHubGitHubSignUp) for your first login, and let us know if you encounter any problems.

Note that if you'd like to use a JupyterHub for a class, we have [lab.openearthscape.org](https://lab.openearthscape.org), where we can quickly set up logins for your students so they won't have to go through this GitHub registration process.
