### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by TitouanHalle** [csdms/help-desk#177]
Thank you for signing up to use the CSDMS JupyterHub. Please provide your CSDMS username and a brief description of why you're signing up (a sentence is fine).

*CSDMS username:*TitouanH

*Describe why you're signing up for an account:*I will work on a modelisation project about craters of Mars during an internship.

Once you've completed this step, you'll typically get approval within one business day.

**Comment by mdpiper** [comment]
👋 @TitouanHalle  -- you're all set! Please follow [these instructions](https://csdms.colorado.edu/wiki/JupyterHubGitHubSignUp#The_first-time_login_process) for your first login, and let us know if you encounter any problems.
