### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by jmjak86** [csdms/help-desk#178]
Thank you for signing up to use the CSDMS JupyterHub. Please provide your CSDMS username and a brief description of why you're signing up (a sentence is fine).

jmjaeger

To use  JupyterHub for accessing the NSF-funded OpenEarthscape project.

Once you've completed this step, you'll typically get approval within one business day.

**Comment by mdpiper** [comment]
👋 @jmjak86  -- you're all set! Please follow [these instructions](https://csdms.colorado.edu/wiki/JupyterHubGitHubSignUp#The_first-time_login_process) for your first login, and let us know if you encounter any problems.
