### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by colinneberarnowil** [csdms/help-desk#179]
Thank you for signing up to use the CSDMS JupyterHub. Please provide your CSDMS username and a brief description of why you're signing up (a sentence is fine).

*CSDMS username: Wilscoli

*Describe why you're signing up for an account: I'm interested in CSDMS labs because they were mentioned by a guest speaker recently in my Intro to Python class. I'm an undergrad in Oregon State University's "biological and ecological engineering" program and I'd like to learn more about analysis of large-scale entities: watersheds, hydrology, that sort of thing. 

Once you've completed this step, you'll typically get approval within one business day.

**Comment by mdpiper** [comment]
👋 @colinneberarnowil -- you're all set! Please follow [these instructions](https://csdms.colorado.edu/wiki/JupyterHubGitHubSignUp#The_first-time_login_process) for your first login, and let us know if you encounter any problems.
