### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by lmcguire** [csdms/help-desk#181]
Thank you for signing up to use the CSDMS JupyterHub. Please provide your CSDMS username and a brief description of why you're signing up (a sentence is fine).

lmcguire

*Describe why you're signing up for an account:*
Participating in landlab clinic at CSDMS.

Once you've completed this step, you'll typically get approval within one business day.

**Comment by mdpiper** [comment]
👋 @lmcguire -- check my email response!
