### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by sebastien-lenard** [csdms/help-desk#183]
Thank you for signing up to use the CSDMS JupyterHub. Please provide your CSDMS username and a brief description of why you're signing up (a sentence is fine).

*CSDMS username:* SebastienLenard

*Describe why you're signing up for an account:* Development of a component that integrates cosmogenic nuclides

Once you've completed this step, you'll typically get approval within one business day.

**Comment by mdpiper** [comment]
👋 @sebastien-lenard  -- you're all set! Please follow [these instructions](https://csdms.colorado.edu/wiki/JupyterHubGitHubSignUp#The_first-time_login_process) for your first login, and let us know if you encounter any problems.
