### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by ale37911** [csdms/help-desk#187]
Thank you for signing up to use the CSDMS JupyterHub. Please provide your CSDMS username and a brief description of why you're signing up (a sentence is fine).

*CSDMS username:* ale37911

*Describe why you're signing up for an account:* I love using the jupyterhub through CSDMS for my classes. I also find it useful for my research to use jupyterhub. I have the old log in that is no longer active and am trying to switch over.

Once you've completed this step, you'll typically get approval within one business day.

**Comment by mdpiper** [comment]
👋 @ale37911 -- you're all set! Please follow [these instructions](https://csdms.colorado.edu/wiki/JupyterHubGitHubSignUp#The_first-time_login_process) for your first login, and let us know if you encounter any problems.
