### ISSUE TITLE
About models installation

### ISSUE THREAD

**Issue by XianaZhang** [csdms/help-desk#19]
Hi guys,
     I came across a confused problem when I was trying to install models from pymt. That is the solving environment was always failed to set.  All models have such a problem for me. As shown below:

(pymt) C:\Users\张明杰>conda install -c conda-forge pymt pymt_sedflux
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/conda-forge/win-64/repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
'https://conda.anaconda.org/conda-forge/win-64'
      
   Hope to get your reply as soon as possible. Very thanks!

**Comment by mdpiper** [comment]
Addressed in https://github.com/csdms/pymt/issues/106.
