### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by shelbyahrendt** [csdms/help-desk#194]
Thank you for signing up to use the CSDMS JupyterHub. Please provide your CSDMS username and a brief description of why you're signing up (a sentence is fine).

*CSDMS username:* Shelbyahrendt

*Describe why you're signing up for an account:* Testing landlab grids and trying to avoid the pain of jumping between my home vs. work computer OS (mac vs windows). Hoping that the JupyterHub smoothes this process!

Once you've completed this step, you'll typically get approval within one business day.

**Comment by mdpiper** [comment]
👋 @shelbyahrendt -- you're all set! Please follow [these instructions](https://csdms.colorado.edu/wiki/JupyterHubGitHubSignUp#The_first-time_login_process) for your first login, and let us know if you encounter any problems.

**Comment by mdpiper** [comment]
P.S. It totally works! @sebastien-lenard pioneered this.
