### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by AlexLipp** [csdms/help-desk#196]
Username: AlexLipp

I'd like to create a notebook for a journal article on the OpenEarthscape jupyterhub as it uses LandLab packages.

**Comment by mdpiper** [comment]
👋 Alex -- you're all set! Please follow [these instructions](https://csdms.colorado.edu/wiki/JupyterHubGitHubSignUp#The_first-time_login_process) for your first login, and let me know if you encounter any problems.
