### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by hsu000001** [csdms/help-desk#197]
Thank you for signing up to use the CSDMS JupyterHub. Please provide your CSDMS username and a brief description of why you're signing up (a sentence is fine).

*CSDMS username:* lhsu

*Describe why you're signing up for an account:*
I'd like to try out this system and help spread the word to my colleagues.

Once you've completed this step, you'll typically get approval within one business day.

**Comment by mdpiper** [comment]
👋 @hsu000001 -- you're all set! Please follow [these instructions](https://csdms.colorado.edu/wiki/JupyterHubGitHubSignUp#The_first-time_login_process) for your first login, and let us know if you encounter any problems.

**Comment by hsu000001** [comment]
I'm in, thank you!!
