### ISSUE TITLE
OpenEarthscape JupyterHub account

### ISSUE THREAD

**Issue by sofiapehli** [csdms/help-desk#199]
Thank you for signing up to use the OpenEarthscape JupyterHub, https://jupyter.openearthscape.org.
Please provide your CSDMS username and a brief description of why you're signing up (a sentence or two is fine).

*CSDMS username:*
Sofia

*Describe why you're signing up for an account:*
I would like to run labs from the CSDMS EKT repository as well as to teach a class at the university. 

Once you've completed this step, you'll typically get approval within one business day.

**Comment by mdpiper** [comment]
👋 @sofiapehli -- you're all set! Please follow [these instructions](https://csdms.colorado.edu/wiki/JupyterHubGitHubSignUp#The_first-time_login_process) for your first login, and let me know if you encounter any problems.

Also, if you're interested, we have a separate JupyterHub ([lab.openearthscape.org](https://lab.openearthscape.org)) that's set up for teaching classes, where it's easy to create logins for your students. If you'd like to use this Hub, let me know!

**Comment by sofiapehli** [comment]
Thanks  a lot!
