### ISSUE TITLE
Binder does not launch from the Pymt examples 

### ISSUE THREAD

**Issue by iovereem** [csdms/help-desk#20]
hi there, 
we are trying to start some of the examples of Pymt models, by trying to open Binder links. 
They do not (always) open, and keep spinning for a really long time (more than 5 minutes). 
We tried from a mac-using a chrome browser, and mac- using a firefox browser. There is no specific error message, only a warning that it 'takes longer than usual to start your instance'. 

Specifically I tried to open: 
https://pymt.readthedocs.io/en/latest/examples.html
Frost Number model
GIPL and ECsimplesnow

**Comment by mdpiper** [comment]
@iovereem We can leave this open for informational purposes, but this is a Binder issue, not a CSDMS issue.

**Comment by mdpiper** [comment]
All *pymt* Notebooks can now be run on the CSDMS JupyterHub. See [here](https://github.com/csdms/pymt/tree/master/notebooks) for instructions on how to sign up for an account.
