### ISSUE TITLE
pymt GIPL not working?

### ISSUE THREAD

**Issue by iovereem** [csdms/help-desk#200]
I am trying to get the pymt-GIPL model working, but it fails with solving packages issues:

On the CSDMS openearthscape jupyter hub, on the CSDMS kernel, I try to run the example notebook: Coupling GIPL and ECSimpleSnow models notebook.

I run the requested install: conda install -c conda-forge pymt pymt_gipl pymt_ecsimplesnow seaborn
It fails on seaborn, so I comment that out and it then appears to pass. 

But then it still does not excecute the code cell to load the GIPL model from pymt. 
AttributeError: module 'pymt.models' has no attribute 'GIPL'

**Comment by mdpiper** [comment]
It looks like I forgot to add GIPL to the CSDMS kernel. I'm sorry about that. It's fixed now, and the [GIPL + ECSimpleSnow models notebook](https://github.com/csdms/pymt/blob/master/notebooks/gipl_and_ecsimplesnow.ipynb) runs to completion.

**Comment by iovereem** [comment]
Yeeh, thank you. It is working

--
Dr. Irina Overeem
CSDMS Community Surface Dynamics Modeling System
INSTAAR, University of Colorado at Boulder
PO Box 450, 80309-0450
Boulder, CO, USA
phone: +1-303-4926631
________________________________
