### ISSUE TITLE
not able to import pymt

### ISSUE THREAD

**Issue by ansine** [csdms/help-desk#202]
I have gone through the install procedure on the webpage several times (copying commands directly off the webpage), but still get the error "no module named "pymt""

It may absolutely be a beginners mistake, but I am not able to figure how what I am doing wrong.

(base) Maria@MacBook-Pro-6 ~ % $ mamba install pymt -c conda-forge
zsh: command not found: $
(base) Maria@MacBook-Pro-6 ~ % mamba install pymt -c conda-forge

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.4.2) supported by @QuantStack

        GitHub:  https://github.com/QuantStack/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████

pkgs/main/osx-64         [====================] (00m:00s) No change
pkgs/r/osx-64            [====================] (00m:00s) No change
pkgs/main/noarch         [====================] (00m:00s) No change
pkgs/r/noarch            [====================] (00m:00s) No change
conda-forge/noarch       [====================] (00m:02s) Done
conda-forge/osx-64       [====================] (00m:06s) Done

Looking for: ['pymt']

Transaction

  Prefix: /Users/Maria/opt/anaconda3

  Updating specs:

   - pymt

  Package               Version  Build                   Channel                  Size
────────────────────────────────────────────────────────────────────────────────────────
  Install:
────────────────────────────────────────────────────────────────────────────────────────

  _anaconda_depends     2020.07  py38_0                  pkgs/main/osx-64         6 KB
  affine                  2.4.0  pyhd8ed1ab_0            conda-forge/noarch      18 KB
  binaryornot             0.4.4  py_1                    conda-forge/noarch     370 KB
  bmipy                     2.0  py_0                    conda-forge/noarch      11 KB
  cem                     0.1.7  hfed58d8_2              conda-forge/osx-64     110 KB
  cftime                  1.6.2  py38hbd87e4b_1          conda-forge/osx-64     221 KB
  child                21.03.12  h940c156_0              conda-forge/osx-64       2 MB
  deprecated             1.2.13  pyh6c4a22f_0            conda-forge/noarch      12 KB
  esmf                    8.1.0  nompi_haa9dfef_0        conda-forge/osx-64      33 MB
  esmpy                   8.1.0  nompi_py38h9b891d1_0    conda-forge/osx-64     173 KB
  geos                   3.11.2  hf0c8a7f_0              conda-forge/osx-64       1 MB
  gimli.units             0.3.0  py38hbd87e4b_2          conda-forge/osx-64      96 KB
  hdf4                   4.2.15  hefd3b78_3              conda-forge/osx-64     885 KB
  hydrotrend              3.1.4  h940c156_0              conda-forge/osx-64     220 KB
  landlab                 2.4.1  py38hbe852b5_0          conda-forge/osx-64       2 MB
  libblas                 3.9.0  9_mkl                   conda-forge/osx-64      12 KB
  libcblas                3.9.0  9_mkl                   conda-forge/osx-64      11 KB
  libgfortran5           12.2.0  he409387_31             conda-forge/osx-64       2 MB
  libglib                2.68.1  hd556434_0              conda-forge/osx-64       3 MB
  liblapack               3.9.0  9_mkl                   conda-forge/osx-64      11 KB
  libllvm9                9.0.1  default_h2671707_4      conda-forge/osx-64      19 MB
  libnetcdf               4.7.4  nompi_h9d8a93f_107      conda-forge/osx-64       1 MB
  model_metadata          0.7.0  pyh9f0ad1d_0            conda-forge/noarch      22 KB
  netcdf-fortran          4.5.3  nompi_h45448fb_103      conda-forge/osx-64     710 KB
  netcdf4                 1.5.6  nompi_py38h2c97785_102  conda-forge/osx-64     430 KB
  pathtools               0.1.2  py_1                    conda-forge/noarch       8 KB
  permamodel              0.1.6  pyh9f0ad1d_0            conda-forge/noarch       8 MB
  platformdirs            2.6.0  pyhd8ed1ab_0            conda-forge/noarch      17 KB
  pooch                   1.7.0  pyha770c72_3            conda-forge/noarch      50 KB
  pymt                    1.3.1  py38hbd87e4b_1          conda-forge/osx-64     138 KB
  pymt_cem                0.1.3  py38hbd87e4b_6          conda-forge/osx-64     126 KB
  pymt_child              0.2.1  py38he49a349_3          conda-forge/osx-64      59 KB
  pymt_hydrotrend         0.2.2  py38hbd87e4b_3          conda-forge/osx-64     112 KB
  pymt_permamodel         0.1.3  py_0                    conda-forge/noarch      11 KB
  pymt_sedflux            0.2.0  py38hbd87e4b_3          conda-forge/osx-64     194 KB
  pyshp                   2.3.1  pyhd8ed1ab_0            conda-forge/noarch     941 KB
  richdem                 0.3.4  py38h4f17bb1_0          conda-forge/osx-64     579 KB
  scripting               0.2.4  py_0                    conda-forge/noarch      13 KB
  sedflux                 2.3.1  hb7837cf_0              conda-forge/osx-64       4 MB
  shapely                 2.0.1  py38he9ee71e_1          conda-forge/osx-64     386 KB
  snappy                 1.1.10  h225ccf5_0              conda-forge/osx-64      34 KB
  udunits2            2.2.27.27  h664449b_1              conda-forge/osx-64     156 KB
  xarray               2022.9.0  pyhd8ed1ab_0            conda-forge/noarch     704 KB

  Upgrade:
────────────────────────────────────────────────────────────────────────────────────────

  ca-certificates     2021.4.13  hecd8cb5_1              installed                    
  ca-certificates    2023.01.10  hecd8cb5_0              pkgs/main/osx-64       Cached
  certifi             2020.12.5  py38hecd8cb5_0          installed                    
  certifi             2022.12.7  pyhd8ed1ab_0            conda-forge/noarch     Cached
  h5py                   2.10.0  py38h3134771_0          installed                    
  h5py                    3.7.0  py38h4a1dd59_0          pkgs/main/osx-64       948 KB
  hdf5                   1.10.4  hfa1e0ec_0              installed                    
  hdf5                   1.10.6  nompi_hc5d9132_1114     conda-forge/osx-64       3 MB
  jpeg                       9b  he5867d9_2              installed                    
  jpeg                       9e  hb7f2c08_3              conda-forge/osx-64     226 KB
  libcxx                 10.0.0  1                       installed                    
  libcxx                 15.0.7  h71dddab_0              conda-forge/osx-64     Cached
  libgfortran             3.0.1  h93005f0_2              installed                    
  libgfortran             5.0.0  12_2_0_h97931a8_31      conda-forge/osx-64     158 KB
  numpy                  1.20.1  py38hd6e1bb9_0          installed                    
  numpy                  1.20.3  py38had91d27_0          conda-forge/osx-64       5 MB
  openssl                1.1.1k  h9ed2024_0              installed                    
  openssl                1.1.1t  hfd90126_0              conda-forge/osx-64       2 MB
  pytables                3.6.1  py38h4727e94_0          installed                    
  pytables                3.7.0  py38h59775c6_1          pkgs/main/osx-64         2 MB
  scipy                   1.6.2  py38hd5f7400_1          installed                    
  scipy                  1.10.1  py38hfb8b963_0          conda-forge/osx-64      21 MB

  Downgrade:
────────────────────────────────────────────────────────────────────────────────────────

  anaconda              2021.05  py38_0                  installed                    
  anaconda               custom  py38_1                  pkgs/main/osx-64        35 KB

  Summary:

  Install: 43 packages
  Upgrade: 11 packages
  Downgrade: 1 packages

  Total download: 115 MB

────────────────────────────────────────────────────────────────────────────────────────

Confirm changes: [Y/n] Y
Finished anaconda                             (00m:00s)              35 KB    122 KB/s                   [>     ] (00m:00s)     36 KB /    948 KB (112.88 KB/s)
Finished jpeg                                 (00m:00s)             226 KB    510 KB/s                   [====================] (00m:00s) Decompressing...
Finished affine                               (00m:00s)              18 KB     38 KB/s                   [====================] (00m:00s) Decompressing...
Finished h5py                                 (00m:00s)             948 KB      2 MB/srtran              [=>    ] (00m:00s)     35 KB /    158 KB ( 72.71 KB/s)
Finished cem                                  (00m:00s)             110 KB    209 KB/s                   [====================] (00m:00s) Decompressing...
Finished libgfortran                          (00m:00s)             158 KB    287 KB/s
Finished geos                                 (00m:00s)               1 MB      2 MB/s                   [==>   ] (00m:00s)    611 KB /      2 MB (783.74 KB/s)
Finished hdf5                                 (00m:00s)               3 MB      3 MB/s                   [====================] (00m:00s) Waiting...
Finished libblas                              (00m:00s)              12 KB     11 KB/s                   [====================] (00m:00s) Waiting...
Finished child                                (00m:00s)               2 MB      2 MB/s                   [====================] (00m:00s) Waiting...
Finished hdf4                                 (00m:00s)             885 KB    809 KB/s                   [>     ] (00m:00s)      2 MB /     33 MB (  1.03 MB/s)
Finished liblapack                            (00m:00s)              11 KB      9 KB/srtran5             [====================] (00m:00s) Decompressing...
Finished libgfortran5                         (00m:00s)               2 MB      1 MB/srtran5             [====================] (00m:00s) Decompressing...
Finished platformdirs                         (00m:00s)              17 KB     12 KB/scdf                [====================] (00m:00s) Waiting...
Finished libnetcdf                            (00m:00s)               1 MB    932 KB/scdf                [====================] (00m:00s) Decompressing...
Finished pathtools                            (00m:00s)               8 KB      6 KB/sols                [====================] (00m:00s) Decompressing...
Finished pymt_permamodel                      (00m:00s)              11 KB      8 KB/sermamodel          [====================] (00m:00s) Decompressing...
Finished netcdf-fortran                       (00m:00s)             710 KB    417 KB/s-fortran           [====================] (00m:00s) Decompressing...
Finished pymt_child                           (00m:00s)              59 KB     34 KB/s                   [====================] (00m:00s) Decompressing...
Finished pyshp                                (00m:00s)             941 KB    544 KB/s                   [====================] (00m:00s) Decompressing...
Finished scripting                            (00m:00s)              13 KB      7 KB/s                   [====================] (00m:00s) Waiting...
Finished pymt                                 (00m:00s)             138 KB     72 KB/s                   [====================] (00m:00s) Decompressing...
Finished shapely                              (00m:00s)             386 KB    179 KB/sy                  [====================] (00m:00s) Decompressing...
Finished udunits2                             (00m:00s)             156 KB     71 KB/s                   [>     ] (00m:00s)    189 KB /      5 MB ( 88.18 KB/s)
Finished binaryornot                          (00m:00s)             370 KB    156 KB/s                   [>     ] (00m:00s)    573 KB /      5 MB (249.88 KB/s)
Finished cftime                               (00m:00s)             221 KB     87 KB/s                   [>     ] (00m:00s)    845 KB /      5 MB (345.88 KB/s)
Finished hydrotrend                           (00m:00s)             220 KB     80 KB/s                   [=>    ] (00m:00s)      2 MB /      5 MB (576.16 KB/s)
Finished esmpy                                (00m:00s)             173 KB     63 KB/s                   [=>    ] (00m:00s)      2 MB /      5 MB (576.16 KB/s)
Finished libcblas                             (00m:00s)              11 KB      4 KB/s                   [==>   ] (00m:00s)      2 MB /      5 MB (813.72 KB/s)
Finished netcdf4                              (00m:00s)             430 KB    111 KB/s                   [===>  ] (00m:01s)      3 MB /      5 MB (859.06 KB/s)
Finished pooch                                (00m:00s)              50 KB     12 KB/s                   [====> ] (00m:02s)      4 MB /      5 MB (940.69 KB/s)
Finished pymt_hydrotrend                      (00m:00s)             112 KB     22 KB/s                   [====>] (00m:03s)      5 MB /      5 MB (1003.87 KB/s)
Finished numpy                                (00m:03s)               5 MB      1 MB/s                   [====================] (00m:03s) Decompressing...
Finished snappy                               (00m:00s)              34 KB      6 KB/ses                 [====> ] (00m:03s)      1 MB /      2 MB (227.85 KB/s)
Finished esmf                                 (00m:08s)              33 MB      6 MB/ses                 [====================] (00m:07s) Waiting...
Finished _anaconda_depends                    (00m:04s)               6 KB      1 KB/sm9                 [====================] (00m:06s) Waiting...
Finished richdem                              (00m:03s)             579 KB    104 KB/sm9                 [====================] (00m:06s) Waiting...
Finished openssl                              (00m:04s)               2 MB    300 KB/sm9                 [====================] (00m:06s) Waiting...
Finished pymt_cem                             (00m:03s)             126 KB     21 KB/sm9                 [====================] (00m:06s) Waiting...
Finished gimli.units                          (00m:03s)              96 KB     16 KB/sm9                 [====================] (00m:06s) Waiting...
Finished pytables                             (00m:07s)               2 MB    270 KB/sm9                 [====================] (00m:06s) Waiting...
Finished libglib                              (00m:03s)               3 MB    454 KB/sb                  [====================] (00m:03s) Decompressing...
Finished model_metadata                       (00m:03s)              22 KB      3 KB/s                   [====================] (00m:03s) Waiting...
Finished deprecated                           (00m:03s)              12 KB      2 KB/s                   [====================] (00m:03s) Waiting...
Finished pymt_sedflux                         (00m:03s)             194 KB     28 KB/s                   [====================] (00m:03s) Waiting...
Finished libllvm9                             (00m:08s)              19 MB      3 MB/s                   [====================] (00m:03s) Waiting...
Finished xarray                               (00m:04s)             704 KB     97 KB/sx                  [====================] (00m:05s) Waiting...
Finished bmipy                                (00m:04s)              11 KB      1 KB/sx                  [====================] (00m:05s) Decompressing...
Finished sedflux                              (00m:05s)               4 MB    502 KB/sx                  [====================] (00m:05s) Decompressing...
Finished permamodel                           (00m:05s)               8 MB    975 KB/sodel               [====================] (00m:05s) Decompressing...
Finished landlab                              (00m:05s)               2 MB    264 KB/sb                  [====================] (00m:05s) Decompressing...
Finished scipy                                (00m:07s)              21 MB      2 MB/s
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(base) Maria@MacBook-Pro-6 ~ % mamba create -n pymt python=3

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.4.2) supported by @QuantStack

        GitHub:  https://github.com/QuantStack/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████

WARNING: A conda environment already exists at '/Users/Maria/opt/anaconda3/envs/pymt'
Remove existing environment (y/[n])? y

pkgs/main/osx-64         [====================] (00m:00s) No change
pkgs/r/osx-64            [====================] (00m:00s) No change
pkgs/main/noarch         [====================] (00m:00s) No change
pkgs/r/noarch            [====================] (00m:00s) No change

Looking for: ['python=3']

Transaction

  Prefix: /Users/Maria/opt/anaconda3/envs/pymt

  Updating specs:

   - python==3

  Package             Version  Build            Channel                Size
─────────────────────────────────────────────────────────────────────────────
  Install:
─────────────────────────────────────────────────────────────────────────────

  bzip2                 1.0.8  h1de35cc_0       pkgs/main/osx-64     Cached
  ca-certificates  2023.01.10  hecd8cb5_0       pkgs/main/osx-64     Cached
  certifi           2022.12.7  py311hecd8cb5_0  pkgs/main/osx-64     Cached
  libffi                3.4.2  hecd8cb5_6       pkgs/main/osx-64     Cached
  ncurses                 6.4  hcec6c5f_0       pkgs/main/osx-64     Cached
  openssl              1.1.1t  hca72f7f_0       pkgs/main/osx-64     Cached
  pip                  23.0.1  py311hecd8cb5_0  pkgs/main/osx-64     Cached
  python               3.11.0  h1fd4e5f_3       pkgs/main/osx-64     Cached
  readline                8.2  hca72f7f_0       pkgs/main/osx-64     Cached
  setuptools           65.6.3  py311hecd8cb5_0  pkgs/main/osx-64     Cached
  sqlite               3.41.1  h6c40b1e_0       pkgs/main/osx-64     Cached
  tk                   8.6.12  h5d9f67b_0       pkgs/main/osx-64     Cached
  tzdata                2022g  h04d1e81_0       pkgs/main/noarch     Cached
  wheel                0.38.4  py311hecd8cb5_0  pkgs/main/osx-64     Cached
  xz                   5.2.10  h6c40b1e_1       pkgs/main/osx-64     Cached
  zlib                 1.2.13  h4dc903c_0       pkgs/main/osx-64     Cached

  Summary:

  Install: 16 packages

  Total download: 0  B

─────────────────────────────────────────────────────────────────────────────

Confirm changes: [Y/n] Y
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate pymt
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) Maria@MacBook-Pro-6 ~ % conda activate pymt
(pymt) Maria@MacBook-Pro-6 ~ % mamba install pymt

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.4.2) supported by @QuantStack

        GitHub:  https://github.com/QuantStack/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████

pkgs/main/osx-64         [====================] (00m:00s) No change
pkgs/main/noarch         [====================] (00m:00s) No change
pkgs/r/osx-64            [====================] (00m:00s) No change
pkgs/r/noarch            [====================] (00m:00s) No change

Looking for: ['pymt']

Encountered problems while solving.
Problem: nothing provides requested pymt

(pymt) Maria@MacBook-Pro-6 ~ % mamba install pymt

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.4.2) supported by @QuantStack

        GitHub:  https://github.com/QuantStack/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████

pkgs/r/osx-64            [====================] (00m:00s) No change
pkgs/main/osx-64         [====================] (00m:00s) No change
pkgs/r/noarch            [====================] (00m:00s) No change
pkgs/main/noarch         [====================] (00m:00s) No change

Looking for: ['pymt']

Encountered problems while solving.
Problem: nothing provides requested pymt

(pymt) Maria@MacBook-Pro-6 ~ % python
Python 3.11.0 (main, Mar  1 2023, 12:49:28) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pymt'
>>>

**Comment by mdpiper** [comment]
You've actually got it--you installed pymt into your base environment with your first call to mamba. If you're currently in an environment, deactivate it to return to the base environment.

In the future, you should need just two commands to create and activate an environment with pymt:
```
mamba create -n pymt python=3.9 pymt
conda activate pymt
```

P.S. Thanks for pasting in the output of the commands--it made it much easier for me to diagnose what went wrong.
