### ISSUE TITLE
OpenEarthscape JupyterHub account

### ISSUE THREAD

**Issue by jhihrouhuang** [csdms/help-desk#203]
Thank you for signing up to use the OpenEarthscape JupyterHub, https://jupyter.openearthscape.org.
Please provide your CSDMS username and a brief description of why you're signing up (a sentence or two is fine).

*CSDMS username:*JhihrouHuang

*Describe why you're signing up for an account:* I am a Ph.D. student at UC Berkeley. I am doing research on the regression model for landslide seismic displacement. I find OpenEarthscape JupyterHub useful in landslide runout estimation. Therefore, I want to have access to OpenEarthscape JupyterHub so I can learn more and make some contributions. 

Once you've completed this step, you'll typically get approval within one business day.

**Comment by mdpiper** [comment]
👋 @jhihrouhuang -- you're all set! Please follow [these instructions](https://csdms.colorado.edu/wiki/JupyterHubGitHubSignUp#The_first-time_login_process) for your first login, and let me know if you encounter any problems.

Also, we have a prototype [Landslide Modeling Portal](https://landslides.openearthscape.org/), with several models and notebook tutorials installed, that may interest you.

**Comment by jhihrouhuang** [comment]
@mdpiper -- Thank you for the help and information! I have authorized OpenEarthscape to access my GitHub account. However, when I sign in OpenEarthscape JupyterHub, the JupyterHub shows 403 forbidden. 

![Screenshot 2023-04-11 204339](https://user-images.githubusercontent.com/69475132/231343721-1df9eda2-6507-4086-af23-b99608d31f8b.jpg)

**Comment by mdpiper** [comment]
@jhihrouhuang I missed a step when setting up your login. I think it's ready now. Please try again & let me know if it works.

**Comment by jhihrouhuang** [comment]
@mdpiper Thank you so much! I can log in to OpenEarthscape successfully now.

**Comment by mdpiper** [comment]
@jhihrouhuang Excellent! Good luck with your work, and please let us know if you encounter any problems with the Hub.
