### ISSUE TITLE
OpenEarthscape JupyterHub account

### ISSUE THREAD

**Issue by ddbuscombe** [csdms/help-desk#205]
Thank you for signing up to use the OpenEarthscape JupyterHub, https://jupyter.openearthscape.org.
Please provide your CSDMS username and a brief description of why you're signing up (a sentence or two is fine).

*CSDMS username:* dbuscombe

*Describe why you're signing up for an account:* I'm interested in experimenting with ways in which jupyterhub applications might leverage existing ML models, so I'd liker to access jupyterhub to test workflows in their intended environment. I'd be interested in working towards developing Data Components that serve ML-generated data grids. This could be done by loading ML output gridded data from a server, or perhaps applying ML models to gridded data on the fly. The former could leverage data as a service, the latter leverages gridded data and models as a service

Once you've completed this step, you'll typically get approval within one business day.

**Comment by mdpiper** [comment]
Hi @dbuscombe-usgs! You're all set. Please follow [these instructions](https://csdms.colorado.edu/wiki/JupyterHubGitHubSignUp#The_first-time_login_process) for your first login, and let me know if you encounter any problems.
