### ISSUE TITLE
OpenEarthscape JupyterHub account

### ISSUE THREAD

**Issue by imt34** [csdms/help-desk#206]
Thank you for signing up to use the OpenEarthscape JupyterHub, https://jupyter.openearthscape.org.
Please provide your CSDMS username and a brief description of why you're signing up (a sentence or two is fine).

*CSDMS username:* Imt34

*Describe why you're signing up for an account:* To run permafrost modeling labs

Once you've completed this step, you'll typically get approval within one business day.

**Comment by mdpiper** [comment]
👋 @imt34 -- you're all set! Please follow [these instructions](https://csdms.colorado.edu/wiki/JupyterHubGitHubSignUp#The_first-time_login_process) for your first login, and let us know if you encounter any problems.
