### ISSUE TITLE
OpenEarthscape JupyterHub account

### ISSUE THREAD

**Issue by geo-dan** [csdms/help-desk#208]
Thank you for signing up to use the OpenEarthscape JupyterHub, https://jupyter.openearthscape.org.
Please provide your CSDMS username and a brief description of why you're signing up (a sentence or two is fine).

*CSDMS username: Dancoastal

*Describe why you're signing up for an account: I am a senior lecturer and researcher at The University of Queensland. I am interested in potentially using OpenEarthscape for teaching in a new geomorphology course here at UQ the I am coordinating but this may also expand into research activities.

Once you've completed this step, you'll typically get approval within one business day.

**Comment by mdpiper** [comment]
👋 @geo-dan -- you're all set! Please follow [these instructions](https://csdms.colorado.edu/wiki/JupyterHubGitHubSignUp#The_first-time_login_process) for your first login and let us know if you encounter any problems.

I'm doing some maintenance on this JupyterHub for the next couple days, so there may be some service interruption.

Also, let me know if you decide to use EarthscapeHub for your new geomorph course. I can help with setup for you and your students.

**Comment by geo-dan** [comment]
Hi Mark,

Thanks so much for that. The course will be revamped over the next two years and for the next semester I am somewhat inclined to role out the binder examples of pymt for some of the practicals given the semester starts in July and getting something new into the teaching system takes a while.

Just out of interest, however, how difficult is it to enrol between 50 - 70 students into Jupyter lab so they can work with notebooks I develop in the CSDMS kernel?

Kind Regards,

Daniel

________________________________

**Comment by mdpiper** [comment]
Creating logins for students is easy--if you provide me with a list of emails, it takes only a few minutes to set them up for a course. Further, if you use a GitHub repository for your course notebooks, there's a way to provision each student with a copy of the repository, so they'll have their own set of notebooks to experiment with.

If it would be easier, please feel free to email me at mark.piper@colorado.edu & I can provide more detail.

**Comment by mdpiper** [comment]
Also, I had to restore this JupyterHub from a backup today, but I was able to recover your files. Drop me a line and I can email them to you.
