### ISSUE TITLE
OpenEarthscape JupyterHub account

### ISSUE THREAD

**Issue by wndlovu** [csdms/help-desk#209]
Thank you for signing up to use the OpenEarthscape JupyterHub, https://jupyter.openearthscape.org.
Please provide your CSDMS username and a brief description of why you're signing up (a sentence or two is fine).

*CSDMS username:* wndlovu@ku.edu

*Describe why you're signing up for an account:*
I would like to use the JypyterHub for some sections of my Master's project with the goal of reducing the computational time. Thank you!

**Comment by mdpiper** [comment]
👋 @wndlovu -- I'm doing some maintenance on this Hub. I hope to be finished today, but it may spill over into tomorrow. I'll set you up with a new login when I'm done. (I'm restoring from a backup, which clobbers any new logins I make.)

**Comment by mdpiper** [comment]
I'm finished with the Hub maintenance, and you're all set! Please follow [these instructions](https://csdms.colorado.edu/wiki/JupyterHubGitHubSignUp#The_first-time_login_process) for your first login and let me know if you encounter any problems.

**Comment by wndlovu** [comment]
Thank you @mdpiper!

**Comment by mdpiper** [comment]
You're welcome! 😄
