### ISSUE TITLE
OpenEarthscape JupyterHub account

### ISSUE THREAD

**Issue by nfakrai** [csdms/help-desk#210]
Thank you for signing up to use the OpenEarthscape JupyterHub, https://jupyter.openearthscape.org.
Please provide your CSDMS username and a brief description of why you're signing up (a sentence or two is fine).

*CSDMS username:* nfakrai

*Describe why you're signing up for an account:* I am a student contractor for the USGS Geomapping for Integrated Science project, and I will be working with colleagues from other projects to collaborate on python coding. I already have a background in computer science, but I want to sign up so that I can familiarize myself with the applications of python in geomorphology and other geoscience-related topics as a foundation for my participation in the USGS project.

Once you've completed this step, you'll typically get approval within one business day.

**Comment by mdpiper** [comment]
👋 @nfakrai -- you're all set! Please follow [these instructions](https://csdms.colorado.edu/wiki/JupyterHubGitHubSignUp#The_first-time_login_process) for your first login, and let us know if you encounter any problems.
