### ISSUE TITLE
OpenEarthscape JupyterHub account

### ISSUE THREAD

**Issue by TheLumiGuy** [csdms/help-desk#211]
Thank you for signing up to use the OpenEarthscape JupyterHub, https://jupyter.openearthscape.org.
Please provide your CSDMS username and a brief description of why you're signing up (a sentence or two is fine).

*CSDMS username: Arindam*

*Describe why you're signing up for an account: I am interested in learning landscape evolution model*

Once you've completed this step, you'll typically get approval within one business day.

**Comment by mdpiper** [comment]
👋 @TheLumiGuy -- you're all set! Please follow [these instructions](https://csdms.colorado.edu/wiki/JupyterHubGitHubSignUp#The_first-time_login_process) for your first login, and let us know if you encounter any problems.
