### ISSUE TITLE
OpenEarthscape JupyterHub account

### ISSUE THREAD

**Issue by gillenmn** [csdms/help-desk#212]
Thank you for signing up to use the OpenEarthscape JupyterHub, https://jupyter.openearthscape.org.
Please provide your CSDMS username and a brief description of why you're signing up (a sentence or two is fine).

mgillen

Want to practice in landlab tutorial notebooks for future use in research. Trying to extract drainage basin and river network data on volcanic ocean islands for global analysis.

Once you've completed this step, you'll typically get approval within one business day.

**Comment by mdpiper** [comment]
👋 @gillenmn -- you're all set! Please follow [these instructions](https://csdms.colorado.edu/wiki/JupyterHubGitHubSignUp#The_first-time_login_process) for your first login, and let me know if you encounter any problems.
