### ISSUE TITLE
OpenEarthscape JupyterHub account

### ISSUE THREAD

**Issue by jrymart** [csdms/help-desk#213]
Request to use the OpenEarthscape JupyterHub, https://jupyter.openearthscape.org.

CSDMS Username: jrymart

Reason: I am signing up to be able to learn how to use Landlab and other CSDMS tools without needing to set up my own environment.

**Comment by mdpiper** [comment]
Hey @jrymart, I didn't see your username on the CSDMS website. Did you sign up?

**Comment by jrymart** [comment]
Howdy!  I did, but just today (9:32 Mountain time) maybe it needs time to propagate through a system?
