### ISSUE TITLE
OpenEarthscape JupyterHub account

### ISSUE THREAD

**Issue by phaedraupton** [csdms/help-desk#215]
Thank you for signing up to use the OpenEarthscape JupyterHub, https://jupyter.openearthscape.org.
Please provide your CSDMS username and a brief description of why you're signing up (a sentence or two is fine).

Pupton:

Hi, 
I'm not sure if I have an account or not but when I tried to login just now as described on this page
https://csdms.colorado.edu/wiki/JupyterHubGitHubSignUp
It doesn't give me the login page, it just says "403 : Forbidden"

I'm wanting to use it for some Landlab modelling.

thanks!
Phaedra

**Comment by mdpiper** [comment]
👋 Phaedra! This is a piece of cake--you just need to have your account authorized. You should now be able to login using the instructions on the page you linked to above.
