### ISSUE TITLE
OpenEarthscape JupyterHub account

### ISSUE THREAD

**Issue by CristinaMarsh** [csdms/help-desk#216]
Dear OpenEarthscape JupyterHub Team,

I hope this email finds you well. I am writing to request approval for my newly created account on the OpenEarthscape JupyterHub platform.

*CSDMS username:* ChristinaMasuki

*Describe why you're signing up for an account:* 
I am keenly interested in leveraging the computational resources and modeling tools available on your platform. My primary research focus is on exploring the impact of climate change on landslide hazards. I believe that the OpenEarthscape JupyterHub will be instrumental in advancing my research objectives.

I understand that the approval process typically takes one business day. I look forward to your positive response and am excited about the prospect of utilizing this valuable resource for my research.

Thank you for considering my application. If you require any further information, please do not hesitate to contact me.

Best regards,
Christina Masuki

**Comment by mdpiper** [comment]
👋 @CristinaMarsh -- you're all set! Please follow [these instructions](https://csdms.colorado.edu/wiki/JupyterHubGitHubSignUp#The_first-time_login_process) for your first login, and let us know if you encounter any problems.
