### ISSUE TITLE
Access to jupyter lab hub for class

### ISSUE THREAD

**Issue by rheadley9** [csdms/help-desk#224]
I’d like to request access to [lab.openearthscape.org](https://lab.openearthscape.org/)
I’d like to possibly use it in my Jan course (5 students) and possibly with my spring research students. My github login is rheadley9, and my csdms login is rheadley, but I don't have lab access yet.
I'm a professor at College of Idaho.
Best,
Rachel

**Comment by mdpiper** [comment]
Hi @rheadley9! I'm using email addresses to set up logins on the _lab_ Hub. Would you please send me (mark dot piper at colorado dot edu) an email with addresses for your students? I can set up accounts for you & them right away. If other students sign up for your course, it's easy to add them, too--just let me know.

**Comment by mdpiper** [comment]
And sorry, if you prefer, I can just set up an account for you now & wait until you decide if you want to use the Hub for your course to add the students.
