### ISSUE TITLE
OpenEarthscape JupyterHub account

### ISSUE THREAD

**Issue by Tanyageo** [csdms/help-desk#226]
Thank you for signing up to use the OpenEarthscape JupyterHub, https://jupyter.openearthscape.org.
Please provide your CSDMS username and a brief description of why you're signing up (a sentence or two is fine).

*CSDMS username:* Tan

*Describe why you're signing up for an account:* I am a graduate student, and I wish to use CSDMS OpenEarthscape JupyterHub serivces for research purposes.

Once you've completed this step, you'll typically get approval within one business day.

**Comment by mdpiper** [comment]
Hi @Tanyageo -- I don't see the username Tan on the CSDMS wiki. Would you check this, please? If you haven't done so, please [sign up](https://csdms.colorado.edu/wiki/Special:RequestAccount) for CSDMS. Thanks!

**Comment by Tanyageo** [comment]
Hi Mark,

Thanks for letting me know. I have just completed the CSDMS form. You might
find my username now on the CSDMS wiki.
Thank you!

**Comment by mdpiper** [comment]
OK, you're all set! Please follow [these instructions](https://csdms.colorado.edu/wiki/JupyterHubGitHubSignUp#The_first-time_login_process) for your first login, and let us know if you encounter any problems.
