### ISSUE TITLE
OpenEarthscape JupyterHub account

### ISSUE THREAD

**Issue by rebreunig** [csdms/help-desk#227]
Thank you for signing up to use the OpenEarthscape JupyterHub, https://jupyter.openearthscape.org.
Please provide your CSDMS username and a brief description of why you're signing up (a sentence or two is fine).

*CSDMS username:* 
RachelBreunig

*Describe why you're signing up for an account:*
I am running landlab to model landscape evolution of subduction zone volcanoes under glacial and interglacial conditions as part of my PhD dissertation, and my computer is unable to handle the size of model! Please let me know if you have additional questions. 

Once you've completed this step, you'll typically get approval within one business day.

**Comment by mdpiper** [comment]
👋 @rebreunig -- you're all set! Please follow [these instructions](https://csdms.colorado.edu/wiki/JupyterHubGitHubSignUp#The_first-time_login_process) for your first login, and let me know if you encounter any problems.

Also, you might be interested in our [frontier](https://csdms.colorado.edu/wiki/JupyterHub#frontier) instance. I can scale it up if you need more memory or processing power for your model.
