### ISSUE TITLE
get JupyterHub accounts for students

### ISSUE THREAD

**Issue by zhouxuanxiao** [csdms/help-desk#228]
Hello! I am a PhD student from Sun Yat-sen University, China and I am writing this message to request an account using CSDMS JupyterHub (for MARSSIM code), Kind thanks!

Zhouxuan Xiao
2024-04-02

**Comment by mdpiper** [comment]
Hi @zhouxuanxiao! I'm happy to set up a JupyterHub account for you, but are you a CSDMS member? If not, it's easy to sign up, see https://csdms.colorado.edu/wiki/Join_CSDMS. Please let me know your CSDMS username and I can proceed.

**Comment by zhouxuanxiao** [comment]
Many thanks for your kind reply, my CSDMS username is **zhoux**.

**Comment by mdpiper** [comment]
👋 @zhouxuanxiao -- you're all set! Please follow [these instructions](https://csdms.colorado.edu/wiki/JupyterHubGitHubSignUp#The_first-time_login_process) for your first login, and let me know if you encounter any problems.
