### ISSUE TITLE
OpenEarthscape JupyterHub account

### ISSUE THREAD

**Issue by thermok-SG** [csdms/help-desk#230]
Thank you for signing up to use the OpenEarthscape JupyterHub, https://jupyter.openearthscape.org.
Please provide your CSDMS username and a brief description of why you're signing up (a sentence or two is fine).

Suryodoyg

I'm a  researcher starting work on using Landlab to develop a new technique to study landslides and how earthquakes influence their distributions in various places across the world. I also plan to develop new components for Landlab. This JupyterHub will make it really easy to carry out experiments on the platform and smooth the process.

Once you've completed this step, you'll typically get approval within one business day.

**Comment by mdpiper** [comment]
👋 @thermok-SG -- you're all set! Please follow [these instructions](https://csdms.colorado.edu/wiki/JupyterHubGitHubSignUp#The_first-time_login_process) for your first login, and let us know if you encounter any problems.
