### ISSUE TITLE
OpenEarthscape JupyterHub account

### ISSUE THREAD

**Issue by thuff621** [csdms/help-desk#231]
Thank you for signing up to use the OpenEarthscape JupyterHub, https://jupyter.openearthscape.org.
Please provide your CSDMS username and a brief description of why you're signing up (a sentence or two is fine).

*CSDMS username:*
thuff621

*Describe why you're signing up for an account:*
I am working with a USACE team that is trying to put together a project for the CSDMS workshop. We are hoping to use the JupyterHub to help facilitate this. 

Once you've completed this step, you'll typically get approval within one business day.

**Comment by mdpiper** [comment]
Hi @thuff621 -- Would you be willing to email me at mark.piper@colorado.edu? I can work with you directly on this.
