### ISSUE TITLE
OpenEarthscape JupyterHub account

### ISSUE THREAD

**Issue by mandli** [csdms/help-desk#232]
Thank you for signing up to use the OpenEarthscape JupyterHub, https://jupyter.openearthscape.org.
Please provide your CSDMS username and a brief description of why you're signing up (a sentence or two is fine).

*CSDMS username:*
mandli

*Describe why you're signing up for an account:*
Helping run one of the tutorials at the CSDMS 2024 meeting.

Once you've completed this step, you'll typically get approval within one business day.

**Comment by mdpiper** [comment]
Hey @mandli -- You have an account on the lab Hub, https://lab.openearthscape.org, which we'll use for the meeting. To login, use the email address you used to sign up for the meeting + pick a password.

**Comment by mdpiper** [comment]
Let me know if you run into any problems!
