### ISSUE TITLE
OpenEarthscape JupyterHub account

### ISSUE THREAD

**Issue by DSayan2709** [csdms/help-desk#233]
Thank you for signing up to use the OpenEarthscape JupyterHub, https://jupyter.openearthscape.org.
Please provide your CSDMS username and a brief description of why you're signing up (a sentence or two is fine).

*CSDMS username:* SayanD (sayand.es2709@gmail.com)

*Describe why you're signing up for an account:*
I am a tectonic geomorphologist, pursuing my PhD at Indiana University, Bloomington. I am attending CSDMS24 as an assistant to Dr. Eyal Marder for his research clinic. I want access to the jupyter interface that the participants of our clinic will be using. I also plan to attend other clinics at the event.

Once you've completed this step, you'll typically get approval within one business day.

**Comment by mdpiper** [comment]
Account set up on _lab_ Hub.
