### ISSUE TITLE
OpenEarthscape JupyterHub account

### ISSUE THREAD

**Issue by mgcooper** [csdms/help-desk#234]
Thank you for signing up to use the OpenEarthscape JupyterHub, https://jupyter.openearthscape.org.
Please provide your CSDMS username and a brief description of why you're signing up (a sentence or two is fine).

*CSDMS username:*
mgcooper

*Describe why you're signing up for an account:*
CSDMS annual meeting clinic

Once you've completed this step, you'll typically get approval within one business day.

**Comment by mdpiper** [comment]
Hey @mgcooper -- You have an account on the _lab_ Hub [https:lab.openearthscape.org](https:lab.openearthscape.org) set up for the meeting. To login, use your work email address (the one you used to sign up for the meeting) + pick a password.
