### ISSUE TITLE
Request for Jupyter Lab account

### ISSUE THREAD

**Issue by DSayan2709** [csdms/help-desk#235]
Hi, my details are as follows:

CSDMS username: SayanD

Account email: sayand.es2709@gmail.com

Work email: saydas@iu.edu

Purpose of lab account: I am attending CSDMS24 as an assistant to Dr. Eyal Marder for his research clinic. I also plan to attend other clinics during my time here. So, I need access to a lab account.
I have also applied for a Jupyter hub account.

**Comment by mdpiper** [comment]
Hey @DSayan2709 -- Use your work email to login to the lab Hub (https://lab.openearthscape.org) + pick a password.
