### ISSUE TITLE
OpenEarthscape JupyterHub account

### ISSUE THREAD

**Issue by vietbuiminh** [csdms/help-desk#237]
Thank you for signing up to use the OpenEarthscape JupyterHub, https://jupyter.openearthscape.org.
Please provide your CSDMS username and a brief description of why you're signing up (a sentence or two is fine).

*CSDMS username:vietbuiminh*

*Describe why you're signing up for an account:clinic for Clawpack*

Once you've completed this step, you'll typically get approval within one business day.

**Comment by mdpiper** [comment]
Hi @vietbuiminh -- I've set up an account for you on the _lab_ Hub using your work email address. You should be able to follow the instructions in the clinic README to login and follow along. Let me know if you encounter any problems.
