### ISSUE TITLE
OpenEarthscape JupyterHub account

### ISSUE THREAD

**Issue by tori543** [csdms/help-desk#239]
Thank you for signing up to use the OpenEarthscape JupyterHub, https://jupyter.openearthscape.org.
Please provide your CSDMS username and a brief description of why you're signing up (a sentence or two is fine).

*CSDMS username:*

tori543

*Describe why you're signing up for an account:*

I hope to create and share a hydrologic and sediment transport model of the Puyallup River, as well as access databases to import information necessary to plug into it!

Once you've completed this step, you'll typically get approval within one business day.

**Comment by mdpiper** [comment]
Hey @tori543 -- I don't see the username tori543 on the CSDMS website. Did you do the [signup](https://csdms.colorado.edu/wiki/Join_CSDMS)? If so, send me the CSDMS username you got from that.

**Comment by tori543** [comment]
hello @mdpiper , I have an account registered... username is Tori543 with a capital T, that might make a difference? Let me know if itworks!

**Comment by mdpiper** [comment]
Thanks, @tori543. You're all set! Please follow [these instructions](https://csdms.colorado.edu/wiki/JupyterHubGitHubSignUp#The_first-time_login_process) for your first login, and let us know if you encounter any problems.
