### ISSUE TITLE
logging into JupyterHub for the first time after authorization error code

### ISSUE THREAD

**Issue by bella-gray** [csdms/help-desk#247]
Hi!

My account just got authorized but when I go to login to JupyterHub through CSDMS, I get a 403 error code. Is there something I'm missing on my end? 

Thanks for your help!

**Comment by mdpiper** [comment]
Oh, I'm sorry--I think I forgot a step in the process of adding a new user. Please try again now & let me know if you can login.

**Comment by bella-gray** [comment]
Works fine now. Thanks!
