### ISSUE TITLE
Recent package updates breaking code?

### ISSUE THREAD

**Issue by paselkin** [csdms/help-desk#249]
Hi folks,
I was wondering if there were recent (last month or so) updates to the jupyterhub environment that might affect how the xarray package works. We have a notebook that we'd been using previously that wasn't giving any errors, but now gives us an error about comparing str and int values whenever we try to print or display an xarray DataArray. Previously we'd been getting a summary of the DataArray.

**Comment by mcflugen** [comment]
@paselkin Does the error you're seeing look anything like the error reported in landlab/landlab#2018?

If so, it's an incompatibility with *Landlab* v2.9.0 and *numpy* v2. If you think this could be the problem, will you please check what version of *numpy* and *landlab* is installed in your environment?
```python
>>> import numpy as np
>>> np.__version__
'2.1.2'
>>> import landlab
>>> landlab.__version__
'2.9.0'
```
I have a fix for this issue ready to go. We just need to install it on our jupyterhub.

**Comment by paselkin** [comment]
Thanks! Yes, it's the same error. We're using jupyterhub on jupyter.openearthscape.org; numpy is 1.26.2. Can I create my own virtual environment within jupyterhub so I can control package versions? Or do I just do something like "!pip install 'numpy>2.0'" in a jupyter instance? I'm not familiar enough with jupyterhub to know that...

**Comment by mdpiper** [comment]
@paselkin Landlab has been updated in the CSDMS kernel of the *jupyter* Hub. Let us know if this fixes the problem you're seeing.

**Comment by paselkin** [comment]
Looks like it works. Thanks!

**Comment by mdpiper** [comment]
Thanks, @paselkin!
