### ISSUE TITLE
Invalid code to verify new account 

### ISSUE THREAD

**Issue by mbbarksdale** [csdms/help-desk#250]
I just signed up for a CSDMS account because I'm trying to publish a model code on the repository but the verification link sent to my email resulted in a broken link that said "Invalid confirmation code. The code may have expired." Please advise!  Thanks!

**Comment by mdpiper** [comment]
Hey @mbbarksdale -- we've all been out at a meeting this past week, but I'll check in with @kettner (our web specialist) when we're back in the office.

**Comment by mbbarksdale** [comment]
Hi Mark,

Thank you so much for the response! I eventually gained access as a new member, so this is no longer a concern.

(I did upload a model to the repository and emailed the help desk again (subject line: "Link to GitHub COLT_Restorations model") to ask a question related to the model as well as provide a link to the GitHub model site. I don't know if those emails are funneled to you or not but wanted to give a heads up if so!)

Best,
Mary Bryan
________________________________

**Comment by mdpiper** [comment]
Hi Mary--just checking, did you get help on the model repository problem you mentioned above?

**Comment by mbbarksdale** [comment]
Hi Mark,

Thank you for checking; yes I did! Albert Kettner helped me.

Best,
Mary Bryan
________________________________

**Comment by mdpiper** [comment]
Oh, good! I'll close this issue.
