### ISSUE TITLE
OpenEarthscape JupyterHub account

### ISSUE THREAD

**Issue by Dewan-cpu** [csdms/help-desk#251]
Thank you for signing up to use the OpenEarthscape JupyterHub, https://jupyter.openearthscape.org.
Please provide your CSDMS username and a brief description of why you're signing up (a sentence or two is fine).

*CSDMS username:*
Dhaque1

*Describe why you're signing up for an account:*

I wish to use JupyterHub to reproduce a few research results on landslide susceptibility assessment
Once you've completed this step, you'll typically get approval within one business day.

**Comment by mdpiper** [comment]
👋 @Dewan-cpu -- you're all set! Please follow [these instructions](https://csdms.colorado.edu/wiki/JupyterHubGitHubSignUp#The_first-time_login_process) for your first login, and let us know if you encounter any problems.

**Comment by Dewan-cpu** [comment]
Hi Dr. Mark: thanks for giving me access to Jupyter Hub.

I am experiencing the following error when uploading my Notebook of interest/any data:
[cid:0d3a19b4-4c31-46a7-b969-e4bba1c37fc1]

Please help!
Sincerely
Dewan
________________________________

**Comment by Dewan-cpu** [comment]
Hi : thanks again for allowing me to use JupyterHub which is really useful for my ongoing research. 

I am experiencing the following issue while digging into any CSDMS page. e.g.
https://csdms.colorado.edu/wiki/Main_Page
Not Found
The requested URL was not found on this server.

Is it due to maintenance of the server or if any other issue. Please confirm.

Sincerely
Dewan
