### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by hsu000001** [csdms/help-desk#27]
Thank you for signing up to use the CSDMS JupyterHub. To get your account authorized, please provide the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*First four characters of username:*
lhsu

*Describe why you're signing up for an account:*
To be able to be backup for a presentation doing a demo on CSDMS JupyterHub (by Rich McDonald.)

Once you've completed these steps, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
@hsu000001 You're all set! Please let me know if there are any problems.

(Aside: Do you think this signup process is OK?)

**Comment by hsu000001** [comment]
Thank you! The signup process is very easy. My problem is that I filtered away all notifications from GitHub out of my inbox at one point, so I forgot all about this until Rich's email. I doubt that would be an issue for many other people.

**Comment by mdpiper** [comment]
Oh, good! Thanks for letting me know. I'm concerned about extra steps in the signup process, and I'm hoping this makes it easier and more transparent.
