### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by rjleveque** [csdms/help-desk#29]
Thank you for signing up to use the CSDMS JupyterHub. To get your account authorized, please provide the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*First four characters of username:*
rjle

*Describe why you're signing up for an account:*
Try out notebooks and think about adding some for GeoClaw.

Once you've completed these steps, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
Hi, @rjleveque! You're all set.

**Comment by rjleveque** [comment]
Thanks!
