### ISSUE TITLE
Access GPU nodes on CSDMS HPC

### ISSUE THREAD

**Issue by mdpiper** [csdms/help-desk#3]
@SwiftHickory writes:

> For my clinic, I'd like to show a demo of our GPU version code. I'd like to ask if there is any available GPU cluster that we can access during the clinic. We have figured out other way to do it but if there is any available one, it will be much easier for us.

**Comment by mdpiper** [comment]
I directed @SwiftHickory to the instructions for getting an account on the CSDMS HPC: https://csdms.colorado.edu/wiki/HPC.

**Comment by mdpiper** [comment]
@SwiftHickory Once you get an account set up on the CSDMS HPC, [here's](https://curc.readthedocs.io/en/latest/running-jobs/job-resources.html) a link that describes the available partitions and QoS levels, including those with GPUs.

**Comment by SwiftHickory** [comment]
Thanks @mdpiper , I have submitted the hpc account application. Once I have the account, I will try and follow the direction you gave.

**Comment by SwiftHickory** [comment]
@mdpiper. Thanks for your help. Now I have the hpc account. I'm now trying to compile our DES3D code. Our code needs libraries tbb, boost and VTK. I didn't find those modules. I'm wondering if it is possible to install those libraries on the system instead of just under my account. So when other users want to use the code, it will save a lot of efforts.

**Comment by mdpiper** [comment]
@SwiftHickory I agree, it would best to have these libraries available systemwide as modules. CU's Research Computing center administers Summit, so they would be the ones to contact with this request. Would you please send an email to rc-help@colorado.edu?

Note that I was able to find tbb and boost with `module spider`, but boost wouldn't load after tbb.
