### ISSUE TITLE
Are these files needed for BMI 2.0? Can you help explain the purpose of these files?

### ISSUE THREAD

**Issue by amoodie** [csdms/help-desk#32]
Hi, a few of us are in the process of updating and improving the [pyDeltaRCM](https://github.com/DeltaRCM/pyDeltaRCM_WMT) numerical model. 

This model was compliant with BMI 1.0 at some point, but was not maintained. We would like to continue to support the BMI, and have chosen to split out the BMI as a wrapper around the core model [in a separate repository](https://github.com/DeltaRCM/BMI_pyDeltaRCM). I've gotten most of the BMI 2.0 setup worked out, I think. Check it out and let me know if you have suggestions!

The question I have though, is what is the purpose of [these files](https://github.com/DeltaRCM/pyDeltaRCM_WMT/tree/911a15cfbcba4214ca471a9ffbffaf1e395a8c5d/.bmi)? The files were last touched by @mdpiper 4 yrs ago. I didn't find anything in the 2.0 specs about these files.

Are these files templates of some kind for the BMI? Can the replaced by adequate documentation? Are they required to be BMI 2.0 compliant? Is there documentation you can point me to for how to update these files? Any information you can provide will be helpful, thanks!

Relates to [#2](https://github.com/DeltaRCM/BMI_pyDeltaRCM/issues/2) in that repo (respond there if you prefer!).

**Comment by mdpiper** [comment]
Hi, @amoodie! It's great that you're working on pyDeltaRCM. We really appreciate it.

The files aren't needed for BMI. It's safe to exclude them.

Some variant of these files will be used to make a new pymt component from your BMI-equipped version of pyDeltaRCM. We can talk about that later, though.

Good luck, and let us know if you have other questions.

**Comment by amoodie** [comment]
Okay, sounds good. I'll close this issue then. 

Should I notify you when we think we have the BMI setup completely ready?

**Comment by mdpiper** [comment]
@amoodie Yes, please let us know! With a little bit of work, we can get your revised version of pyDeltaRCM into pymt.
