### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by benbovy** [csdms/help-desk#37]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:* Bbovy

*First four characters of username:* bbov

*Describe why you're signing up for an account:* CSDMS ESPIn 2020

Once you've completed this step, you'll typically get an approval within one business day.

Thanks!

**Comment by mdpiper** [comment]
@benbovy All set! Let me know if I can help with anything!

**Comment by benbovy** [comment]
Thanks @mdpiper, it works great.
