### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by olusolayemi** [csdms/help-desk#38]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:* 
AdeyemiOlusola

*First four characters of username:* 
ao.ol

*Describe why you're signing up for an account:*
To learn more and become a solid researcher

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
@olusolayemi You're all set--let us know if you have any questions!
