### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by eyalmarder** [csdms/help-desk#39]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:* Eyalmarder

*First four characters of username:* Eyal

*Describe why you're signing up for an account:* ESPIN 2020 workshop

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
@eyalmarder You're all set!
