### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by fdedonck** [csdms/help-desk#40]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:*
fdedonck

*First four characters of username:*
fded

*Describe why you're signing up for an account:*
I'm an attendee of the 2020 ESP In Summer School

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
@fdedonck You're all set!
