### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by elbeejay** [csdms/help-desk#41]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:* Jhariharan

*First four characters of username:* Jhar

*Describe why you're signing up for an account:* ESPIn2020

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
@elbeejay I don't see your username in the list--did you sign up at https://csdms.rc.colorado.edu/hub/signup?

**Comment by elbeejay** [comment]
Ah no, sorry! I thought having a CSDMS sign-up was enough. Just filled it out, thanks. - Jay

**Comment by mdpiper** [comment]
Hi, Jay! Yeah, we have to fix this with OAuth or something similar. Sorry about that. You're all set!
