### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by rmallen86** [csdms/help-desk#42]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:* Rachelallen

*First four characters of username:* rmal

*Describe why you're signing up for an account:* it was requested by the instructors for the ESPIn course

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
@rmallen86 You're all set!
