### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by yuvalsmilo** [csdms/help-desk#43]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:*
Yuvalshmilo

*First four characters of username:*
Yuva

*Describe why you're signing up for an account:*
ESPIn summer course 2020

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
@yuvalsmilo You're all set!
