### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by josiearcuri** [csdms/help-desk#45]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:*
Josiearcuri

*First four characters of username:*
josi

*Describe why you're signing up for an account:*
I'm signing up in preparation for ESPIn 2020

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
@josiearcuri  I don't see your username in the list--did you sign up at https://csdms.rc.colorado.edu/hub/signup?

**Comment by josiearcuri** [comment]
?I must have missed a step, now it is done!

________________________________

**Comment by mdpiper** [comment]
No problem--you're all set now!
