### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by edsaac** [csdms/help-desk#46]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:* esaavedrac

*First four characters of username:* edsa

*Describe why you're signing up for an account:* ESPIn 2020

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
@edsaac  I don't see your username in the list--did you sign up at https://csdms.rc.colorado.edu/hub/signup?

**Comment by edsaac** [comment]
Ah, I was missing that step. It should appear now.
Thank you.

**Comment by mdpiper** [comment]
No problem--you're all set now!
