### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by collinjroland** [csdms/help-desk#48]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:*
Cjroland

*First four characters of username:*
Cjro

*Describe why you're signing up for an account:*
ESPIn summer school participant

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
@collinjroland You're all set!

**Comment by collinjroland** [comment]
Thanks Mark! I mistakenly sent in multiple, look forward to meeting you
later this week!

Collin


Collin Roland (he/him)
-
Graduate Teaching and Research Assistant
University of Wisconsin Department of Geoscience
cjroland@wisc.edu
(214)850-8391

**Comment by mdpiper** [comment]
Hey Collin--it's OK, I approved both; you can use either login.
