### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by huxiaoni** [csdms/help-desk#49]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username: huxiaoni

*First four characters of username: huxi

*Describe why you're signing up for an account: a requirement for the ESPin summer school

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
@huxiaoni You're all set!
