### ISSUE TITLE
Batch job submission failed: Invalid account or account/partition combination specified

### ISSUE THREAD

**Issue by SwiftHickory** [csdms/help-desk#5]
Hi @mdpiper, I'm trying to run the job with sbatch. Here is my job script

#!/bin/bash

#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --time=00:10:00
#SBATCH --partition=shas
#SBATCH --qos=normal
#SBATCH --output=cc2dcpu-%j.out
#SBATCH --error=cc2dcpu-%j.err

module load intel/17.0.0
module load tbb/17.0.0
module load impi/2017.0.098
module load boost/1.64.0

export OMP_NUM_THREADS=8

../../dynearthsol2d_cpu core-complex.cfg

When I submit the job, it says:
sbatch: error: Batch job submission failed: Invalid account or account/partition combination specified

Did I miss something? Thanks.

**Comment by mdpiper** [comment]
@SwiftHickory It may be this: from the login node, before submitting the job, load slurm for summit with
```bash
module load slurm/summit
```

**Comment by SwiftHickory** [comment]
@mdpiper. It still does not work.

When my account was set up, the rc help people mentioned that:

Note: you are not set up for Summit, CSDMS would have to set up a Project and add you to it for you to be able to use Summit.

Is it because of this?

When I try module load slurm/blanca and run the job. There is no such error.

**Comment by mdpiper** [comment]
@SwiftHickory Yes, this is the issue. The sgpu partition is only available on Summit, not Blanca.

I'll look into setting up a project for you. I don't know what this entails, though, so I can't promise that it'll be ready in time for the CSDMS meeting next week.

**Comment by mdpiper** [comment]
@SwiftHickory I worked with RC to set up a project. (It was easier than I thought it would be.) You should now be able to access Summit. Please try, and let me know how it goes!

Also, RC will look into reserving a GPU node for your clinic. Hopefully this will decrease or eliminate queue wait times.

**Comment by SwiftHickory** [comment]
@mdpiper Thanks for you help, I tried it and it works now! Also thanks for reserving the GPU node. It will definitely help.
