### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by hgudipati** [csdms/help-desk#50]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:*
Hgudipati

*First four characters of username:*
Hgud

*Describe why you're signing up for an account:*
ESPIn participant

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
@hgudipati I don't see your username in the list--did you sign up at https://csdms.rc.colorado.edu/hub/signup?

**Comment by hgudipati** [comment]
I just signed up. Did it work?

**Comment by mdpiper** [comment]
Yes, you're all set!
