### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by ericbarefoot** [csdms/help-desk#53]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

ericbarefoot

eric

To participate in the CSDMS ESPin tomorrow! :)

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
@ericbarefoot You're all set!
