### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by tianyuequ** [csdms/help-desk#57]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:*
Qty

*First four characters of username:*
tian

*Describe why you're signing up for an account:*
I am signing up for ESPIn 2020 summer class.

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
@tianyuequ You're all set!
