### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by xlia62** [csdms/help-desk#58]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:*
xueliang

*First four characters of username:*
xuel

*Describe why you're signing up for an account:*
1) for ESPIN workshop.
2) learn land lab and its components.
 
Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
@xlia62 You're all set!
