### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by shelbyahrendt** [csdms/help-desk#61]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:*
shelbyahrendt

*First four characters of username:*
shelb

*Describe why you're signing up for an account:*
I'm looking forward to using it in ESPIn!

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
@shelbyahrendt You're all set!
