### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by cmasteller** [csdms/help-desk#62]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:*
cmasteller

*First four characters of username:*
cmas

*Describe why you're signing up for an account:*
teaching CSDMS hosted labs

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
@cmasteller Your login is all set! I'd like to talk a little about what you're teaching, but I'm teaching [ESPIn](https://csdms.colorado.edu/wiki/ESPIn2020) this week & next, so I'll get back to you as soon as I can.

**Comment by mdpiper** [comment]
Hi @cmasteller! When you have a moment, would you please email me at mark.piper@colorado.edu? I'd like to talk, briefly, about how you'd like to use the CSDMS JupyterHub for class. Thanks!
