### ISSUE TITLE
Errors when trying to do lab 9 and 11

### ISSUE THREAD

**Issue by cctrunz** [csdms/help-desk#63]
I tried lab 9 and lab 11, and could not find a run online button. I downloaded the .ipynb and try to run it on my mac with jupyter from Anaconda. Is more installation required, or should there be an online button?
https://csdms.colorado.edu/wiki/Lab-0009
https://csdms.colorado.edu/wiki/Lab-0011

**For lab 9 when I run this cell:**

`my_movie, model = run_model()`
`my_movie`

I get this issue:

KeyError                                  Traceback (most recent call last)
~/anaconda3/lib/python3.6/site-packages/matplotlib/animation.py in __getitem__(self, name)
    160         try:
--> 161             return self.avail[name]
    162         except KeyError:

KeyError: 'ffmpeg'

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
<ipython-input-4-397356ebdee7> in <module>
----> 1 my_movie, model = run_model()
      2 my_movie

<ipython-input-3-90f08c1f8398> in run_model(run_duration, valley_length, valley_slope, ela, gamma, flow_law_coefficient, ice_density, sliding_factor, grav_accel, num_nodes, timestep_duration, save_every)
     91 
     92     # Convert the animation to HTML
---> 93     vid = HTML(anim.to_html5_video())  # or HTML(anim.to_jshtml())
     94 
     95     report_values(model)

~/anaconda3/lib/python3.6/site-packages/matplotlib/animation.py in to_html5_video(self, embed_limit)
   1324                 # We create a writer manually so that we can get the
   1325                 # appropriate size for the tag
-> 1326                 Writer = writers[rcParams['animation.writer']]
   1327                 writer = Writer(codec='h264',
   1328                                 bitrate=rcParams['animation.bitrate'],

~/anaconda3/lib/python3.6/site-packages/matplotlib/animation.py in __getitem__(self, name)
    162         except KeyError:
    163             raise RuntimeError(
--> 164                 'Requested MovieWriter ({}) not available'.format(name))
    165 
    166 

RuntimeError: Requested MovieWriter (ffmpeg) not available

**and for lab 11**, I get a "No module named 'landlab'".

**Comment by mdpiper** [comment]
@iovereem and @gantian127 Would you please look at this when you have time?

**Comment by gantian127** [comment]
@cctrunz Those two labs are not setup on the CSDMS JupyterHub and that is why there is no run online button. So when the two labs are downloaded, the users need to install some of the required packages. 
For lab 11, the error messages indicates that you need to install landlab python package. 
For lab 9, users need to install FFmpeg. I tested the following command on my mac, and it fixes the issue to run lab 9. $sudo conda install -c conda-forge ffmpeg

**Comment by mdpiper** [comment]
@cctrunz Labs 9 and 11 can now be run on the CSDMS JupyterHub, and the "Run online" link in each will start them there. I also included under the "Requirements" section in each lab a list of the Python packages that would need to be installed if you downloaded the labs and wanted to run them locally.

If you think these improvements are satisfactory, let me know & I'll close this issue.

**Comment by cctrunz** [comment]
@mdpiper, Yes, these improvements are satisfactory.
I've tried both lab 9 and 11 with the run online and it works perfectly now!
this is great! thanks a lot!

**Comment by mdpiper** [comment]
@cctrunz Awesome! Thanks for checking that they're working. I'll close this issue.
