### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by ebaynes9876** [csdms/help-desk#64]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

e.baynes@lboro.ac.uk

ebay

I am an academic in the Geography department at Loughborough University (UK) and would like to explore the labs available online.

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
@ebaynes9876 You're all set! As you explore the labs, please let us know (through the Help Desk) if you find any problems.
