### ISSUE TITLE
CSDMS JupyterHub account 

### ISSUE THREAD

**Issue by luizbacelar** [csdms/help-desk#67]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username: Luizbacelar90

*First four characters of username: Luiz

*Describe why you're signing up for an account: River Discharge Data Analysis

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
@luizbacelar You're all set!
