### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by andyrightmire** [csdms/help-desk#68]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:* atrigh23

*First four characters of username:* atri

*Describe why you're signing up for an account:* I am a student at Colby College. This account is required for my geomorphology class.

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
@andyrightmire You're all set!
