### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by qmdoyl22** [csdms/help-desk#69]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username: qmdoyl22

*First four characters of username: qmdo

*Describe why you're signing up for an account: I will be using it for my class at Colby College.

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
Hi @qmdoyl22 I don't see your username on the list--did you sign up at https://csdms.rc.colorado.edu/hub/signup?

**Comment by qmdoyl22** [comment]
Hi @mdpiper Thanks for the quick response and sorry I was not signed up, but I believe I am now with the username mentioned above.

**Comment by mdpiper** [comment]
@qmdoyl22 Yup, I see you there now--you're all set!
