### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by almack22** [csdms/help-desk#70]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:* Almack22

*First four characters of username:* alma

*Describe why you're signing up for an account:* School and Learning to code

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
Hi @almack22 -- I don't see your username on the list; did you sign up at https://csdms.rc.colorado.edu/hub/signup?

**Comment by mdpiper** [comment]
@almack22 I see that you've made two logins. You can use either, but recognize that they're separate accounts.
