### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by dmalia** [csdms/help-desk#72]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

Dominicm

Domi

Geomorphology course at Colby College

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
Hi @dmalia -- -- I don't see your username on the list; did you sign up at https://csdms.rc.colorado.edu/hub/signup?

**Comment by dmalia** [comment]
My username is Dominicm, I signed up at https://csdms.colorado.edu/wiki/Special:RequestAccount

**Comment by mdpiper** [comment]
@dmalia Ah, yes, that's your CSDMS account. The login for the JupyterHub is separate.

**Comment by dmalia** [comment]
I don't think I can access the JupyterHub because I was never asked to make a password for my CSDMS account.  I only have the Dominicm username.

**Comment by dmalia** [comment]
I have found my CSDMS password, but I have not received anything regarding JupyterHub info.  How do I set up a JupyterHub so I can sign in here: https://csdms.rc.colorado.edu/hub/login ?

**Comment by mdpiper** [comment]
@dmalia Your username and password on the JupyterHub can be anything you like. This is separate from the CSDMS account. Just let me know when you've made it & I'll approve it.

**Comment by dmalia** [comment]
I entered a new username and password but it says its invalid.  The link seems to be a sign in rather than a sign up.  Where can I go to create a JupyterHub login?

**Comment by mdpiper** [comment]
@dmalia Yes, see my original comment upthread for the signup link.

**Comment by dmalia** [comment]
Got it, thanks.  I entered a username and password.

**Comment by mdpiper** [comment]
@dmalia OK, you're all set!
