### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by esdomo23** [csdms/help-desk#76]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:*
Evan.Domonkos

*First four characters of username:*
esdo

*Describe why you're signing up for an account:*
For my Geomorphology Class

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
@esdomo23 You're all set!
