### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by SandraL10** [csdms/help-desk#77]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

slewis23

slew

Class requirement to use for labs

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
@SandraL10 You're all set!
