### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by shbu1400** [csdms/help-desk#78]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:* shbu1400

*First four characters of username:* shbu

*Describe why you're signing up for an account:* I am a student learning to code and model.

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
Hi @shbu1400 -- I don't see your username on the list; did you sign up at https://csdms.rc.colorado.edu/hub/signup?

**Comment by shbu1400** [comment]
I did just now. This is my first time seeing that link. Hope this helps.

Thank you

**Comment by mdpiper** [comment]
@shbu1400 OK, you're all set!
