### ISSUE TITLE
Question about PyPI packaging: wheel includes non-any

### ISSUE THREAD

**Issue by kbarnhart** [csdms/help-desk#8]
@mcflugen and @mdpiper I'm currently working on packaging terrainbento to distribute via PyPI. I had a question about CI and thought it best to ask it here. Context first, and the actually question is at the very bottom of the page. 

I'm copying the approach that @mcflugen has done for Landlab. 

I've gotten to the point where I have successfully upload a wheel to PyPI :tada:

However, only one of my Travis build succeeded, and the others failed with an error like:
```
1.00s$ twine upload -u katybarnhart -p$TWINE_PASSWORD --verbose dist/*terrainbento*
Uploading distributions to https://upload.pypi.org/legacy/
Uploading terrainbento-1.1b2-py3-none-any.whl
100%|██████████| 257k/257k [00:00<00:00, 291kB/s] 
Content received from server:
<html>
 <head>
  <title>400 File already exists. See https://pypi.org/help/#file-name-reuse</title>
 </head>
 <body>
  <h1>400 File already exists. See https://pypi.org/help/#file-name-reuse</h1>
  The server could not comply with the request since it is either malformed or otherwise incorrect.<br/><br/>
File already exists. See https://pypi.org/help/#file-name-reuse
 </body>
</html>
HTTPError: 400 Client Error: File already exists. See https://pypi.org/help/#file-name-reuse for url: https://upload.pypi.org/legacy/
```
[link to travis build](https://travis-ci.org/TerrainBento/terrainbento/jobs/565689421#L1201)

I think that this error has something to do with the name of the wheel, `terrainbento-1.1b2-py3-none-any.whl`. I expected that the `none-any` section would have included some information about the OS. I found information on PyPI indicating that `none-any` means [that my wheel is cross platform](https://packaging.python.org/tutorials/packaging-projects/?highlight=none-any#generating-distribution-archives).

I think this makes sense as terrainbento (unlike Landlab) doesn't require any compilation. 

**Am I correct in thinking that its OK that I just make one wheel. I can thus change my CI to just make one wheel and move forward?**

**Comment by mdpiper** [comment]
@kbarnhart You are correct! Because terrainbento is pure Python, you need only one Python 3 wheel.

**Comment by kbarnhart** [comment]
@mdpiper thanks! I might be a bit confused. terrainbento isn't pure python... (what I would call something with no dependencies). And it depends on things that need platform specific compilation (e.g., landlab). BUT, it itself doesn't need compilation. 

Either way, sounds like I can just change the CI to only build one wheel and call it good.
