### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by sabr6374** [csdms/help-desk#80]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:*
sabr6374

*First four characters of username:*
sabr

*Describe why you're signing up for an account:*
Required material for a college class 

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mcflugen** [comment]
@sabr6374 You should be all set!
