### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by amst7410** [csdms/help-desk#81]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:*
amst7410

*First four characters of username:*
amst

*Describe why you're signing up for an account:*
For research (Brian Hynek) and for the GEOL 5700 class

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
@amst7410 You're all set!

**Comment by amst7410** [comment]
Mark, 

I just tried to log into JupyterHub, and it didn't work. Will it take a day to process? 

Thank you so much, sorry for my confusion. 

Amanda

**Comment by mdpiper** [comment]
Hmm, your login is "Amst7410", and I'm pretty sure it's case-sensitive. Is this what you tried?

**Comment by amst7410** [comment]
That's it, thank you! I didn't realize the capital A!

Amanda

**Comment by mdpiper** [comment]
Oh, good! I'm glad this works. Thanks for checking.
