### ISSUE TITLE
sea born library on the CSDMS jupyter hub?

### ISSUE THREAD

**Issue by iovereem** [csdms/help-desk#82]
Can i use the python seaborn plotting library on the CSDMS jupyter hub? 
If not, could you install it? 

Thanks! Irina

**Comment by mdpiper** [comment]
@iovereem It's installed.

**Comment by iovereem** [comment]
Can I give you a thumbs up in github? thank you!

--
Dr. Irina Overeem
CSDMS Community Surface Dynamics Modeling System
INSTAAR, University of Colorado at Boulder
PO Box 450, 80309-0450
Boulder, CO, USA
phone: +1-303-4926631
________________________________

**Comment by mdpiper** [comment]
You betcha!
