### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by Connorvartanian** [csdms/help-desk#83]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:*
Connorvartanian

*First four characters of username:*
Conn

*Describe why you're signing up for an account:*
Sedimentary Modeling Class

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
@Connorvartanian You're all set!

@iovereem Since you're an admin on the JupyterHub, you can also approve user logins: https://csdms.rc.colorado.edu/hub/authorize
