### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by crosbyben** [csdms/help-desk#84]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:*
crosby

*First four characters of username:*
cros

*Describe why you're signing up for an account:*
To teach a graduate geomorphology class.  Glad to talk about options with anyone available.

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
@crosbyben You're all set! If you'd like to talk more about setting up your class on the JHub, drop me a line: mark dot piper at colorado dot edu.
