### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by ambramson** [csdms/help-desk#85]
Hi,

*CSDMS username:*
bramson

*First four characters of username:*
bram

*Describe why you're signing up for an account:*
I am a new assistant professor at Purdue University and am teaching Earth and Planetary Surface Processes this semester...looking into potentially using some of your labs in my class.

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
Hi @ambramson -- you're all set. Let me know if you're interested in setting up logins for your students on the CSDMS JupyterHub. We've done this for a few other professors this semester. You can email me directly at mark.piper@colorado.edu.
