### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by corasiebert** [csdms/help-desk#86]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

CSDMS username: csiebert

First four characters of username: csie

Describe why you're signing up for an account: Interest in experimenting with the CSDMS labs

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
Hey @corasiebert -- I don't see your name on the list. Did you create a login at https://csdms.rc.colorado.edu/hub/signup?

**Comment by corasiebert** [comment]
Thanks @mdpiper , missed that step! Just created one using the link.

**Comment by mdpiper** [comment]
@corasiebert Got it--you're all set!
