### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by erkanistan** [csdms/help-desk#87]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:*
erkani

*First four characters of username:*
erka

*Describe why you're signing up for an account:*
Teach a class

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
Hi Erkan! You're all set. I can help set up accounts for your students, too, if you'd like--just email me directly.
