### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by awickert** [csdms/help-desk#88]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:*
awickert

*First four characters of username:*
awic

*Describe why you're signing up for an account:*
Developing teaching materials for hydrology + geomorphology

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
Hi, Andy! You're all set.
