### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by KateLeary** [csdms/help-desk#89]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:*
kleary

*First four characters of username:*
klea

*Describe why you're signing up for an account:*
I would like an account to run labs for my course through the jupyter hub. In addition to myself needing an account, do my students each need individual accounts or is there a way to get one account for the course they could all use? Thank you for your help!

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
Hi @KateLeary -- you're all set! Would you please email me at mark.piper@colorado.edu & we can talk about your class + student logins.
