### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by dtrobins** [csdms/help-desk#90]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:*

dtrobins

*First four characters of username:*

dtro

*Describe why you're signing up for an account:*

would like to gain access to ESPin content and gain experience with CSDMS jupyter hub tools

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
@dtrobins You're all set! And check out our ESPIn material here: https://github.com/csdms/espin.
