### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by amalone-UIC** [csdms/help-desk#93]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:*
Amalone

*First four characters of username:*
Amal

*Describe why you're signing up for an account:*
Hoping to use the CSDMS Labs in a geomorphology course that I am teaching in the Spring semester.

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
@amalone-UIC You're all set! When it's convenient, drop me a line at mark.piper@colorado.edu & we can discuss getting logins for the students in your class.
