### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by tom-farr** [csdms/help-desk#95]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:*
Tfarr

*First four characters of username:*
Tfar

*Describe why you're signing up for an account:*
Modeling planetary surficial processes and groundwater. 

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
@tom-farr You're all set! Let us know if you have any questions.
