### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by jacobamorgan** [csdms/help-desk#98]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:*
jamorgan

*First four characters of username:*
jamorgan

*Describe why you're signing up for an account:*
To help in teaching a sediment transport course.

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
@jacobamorgan You're all set! Let me know if you have any questions.
