### ISSUE TITLE
CSDMS JupyterHub account

### ISSUE THREAD

**Issue by peckhams** [csdms/help-desk#99]
Thank you for signing up to use the CSDMS JupyterHub. To complete the signup, please provide your CSDMS username, the first four characters of your username on the CSDMS JupyterHub, as well as a brief description of why you're signing up (a single sentence is fine).

*CSDMS username:*. peckhams

*First four characters of username:* peck

*Describe why you're signing up for an account:*To be able to host workshops with Jupyter notebooks.

Once you've completed this step, you'll typically get an approval within one business day.

**Comment by mdpiper** [comment]
@peckhams You're all set!
